### ISSUE TITLE
cfg->cred_store->count uninitialized

### ISSUE THREAD

**Issue by walt-k** [modauthgssapi/mod_auth_gssapi#10]
Hello
The var cfg->cred_store->count is not initialized (I expect to 0) when allocating cfg->cred_store in mag_cred_store().

**Comment by simo5** [comment]
cfg->cred_store is allocated with apr_pcalloc() which zeros all structure members, therefore count is 0 after allocation.
Are you experiencing any issue with the counter ?

**Comment by walt-k** [comment]
Thank you for your response.
I think, you should put initialization for better understanding of your code.
