### ISSUE TITLE
GSSAPIImpersonate not honoring <proxy> directive?

### ISSUE THREAD

**Issue by splashx** [modauthgssapi/mod_auth_gssapi#101]
When using "GSSAPIImpersonate On" inside a `<Location>` block I get the credential cache created as expected.
However, when switching the very same block and using `<Proxy>` instead of `<Location>` the log file on apache reads:

> [Mon Aug 15 15:13:18.101472 2016] [auth_gssapi:debug] [pid 10048:tid 140052006569728] mod_auth_gssapi.c(656): [client 10.10.0.208:58124] GSSapiImpersonate not On, skipping impersonation.

Any special reason why that happens?

**Comment by simo5** [comment]
It is not intentional, but I do not know why it happens.

**Comment by frenche** [comment]
I can't see why it would differ, can you share a minimal configuration that demonstrate the problem?

**Comment by simo5** [comment]
I see no reproducer here, closing.
