### ISSUE TITLE
Build fails on systems without credential store

### ISSUE THREAD

**Issue by relghuar** [modauthgssapi/mod_auth_gssapi#106]
Following compile error appears:
```
/appl/home/cmpcn/build/apache24/build/libtool --silent  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -I ./asn1c  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -g -O2 -pthread    -I/appl/home/cmpcn/build/apache24/include  -I/appl/home/cmpcn/build/apache24/include  -g -O2 -MT mod_auth_gssapi_la-mod_auth_gssapi.lo -MD -MP -MF .deps/mod_auth_gssapi_la-mod_auth_gssapi.Tpo -c -o mod_auth_gssapi_la-mod_auth_gssapi.lo `test -f 'mod_auth_gssapi.c' || echo './'`mod_auth_gssapi.c
mod_auth_gssapi.c: In function 'mag_auth':
mod_auth_gssapi.c:1003: warning: implicit declaration of function 'mag_complete'
mod_auth_gssapi.c: At top level:
mod_auth_gssapi.c:1092: error: static declaration of 'mag_complete' follows non-static declaration
mod_auth_gssapi.c:1003: note: previous implicit declaration of 'mag_complete' was here
make[2]: *** [mod_auth_gssapi_la-mod_auth_gssapi.lo] Error 1
```
The reason for this is the first declaration of mag_complete in mod_auth_gssapi.c:629 is inside an "#ifdef HAVE_CRED_STORE" block, but not all of its uses are wrapped in such blocks.
Fix is simple - just move mag_complete before the ifdef beginning on line 615.
How to reproduce: just try building the module on a system with krb5 1.10 - RHEL or Oracle Linux <=6.8 for example.

**Comment by simo5** [comment]
Can you check the fix works for you ?

**Comment by relghuar** [comment]
Hi, I had to put the patched mod_auth_gssapi.c file into 1.4.1 release, because GIT pull is missing configure and RHEL 6.7 has too old versions of practically all necessary autoconf tools :-)
But yes, I can confirm that with this fix I could build the project successfully.
