### ISSUE TITLE
Provide authentication persistence even for single roundtrip mechs

### ISSUE THREAD

**Issue by michael-o** [modauthgssapi/mod_auth_gssapi#109]
It would be handy if one could persist authentication on the connection for single roundtrip mechs like Kerberos for clients which do not store/use cookies.

Something like: `GssapiConnectionBound Always`

**Comment by frenche** [comment]
As discussed at #108 this is already how GssapiConnectionBound works (always).

**Comment by michael-o** [comment]
Exactly.
