### ISSUE TITLE
Using Basic authentication: Unspecified GSS failure.  Minor code may provide more information (Ticket expired)

### ISSUE THREAD

**Issue by devurandom** [modauthgssapi/mod_auth_gssapi#11]
When I try to login to my webserver from a non-Kerberos enabled browser (machine does NOT use Kerberos authentication and `network.negotiate-auth.trusted-uris` is NOT set in Firefox), authentication fails and I see following error message in the server logs:
```
[auth_gssapi:error] … gss_init_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Ticket expired)]
```

Initially I also got:
```
[auth_gssapi:error] … In Basic Auth, gss_acquire_cred_with_password() failed: [Unspecified GSS failure.  Minor code may provide more information (Principal in credential cache does not match desired name)]
```
This message currently does not appear, but I have seen it a long time ago already. So it seems to show up randomly?

Login using a Kerberos enabled browser (i.e. machine uses Kerberos authentication and `network.negotiate-auth.trusted-uris` is set in Firefox) succeeds, so this seems to affect only Basic authentication.

I use following Apache config:
```apache
                <Location /auth/login/RemoteUser:self>
                        AuthName "???"
                        AuthType GSSAPI

                        GssapiBasicAuth On
                        GssapiCredStore keytab:/etc/apache2/http.keytab

#                       GssapiConnectionBound On
#                       Header set Persistent-Auth "true"

#                       GssapiUseSessions On
#                       Session On
#                       SessionCookieName gssapi_session path=/;httponly;secure;

                        Require valid-user
                </Location>
```

The commented out parts were in use (and the client also authenticated several times during the time they were enabled), but to limit the testcase I removed them for now.

The machine's clock is synchronised via NTP and I checked that the time is correct.

I am currently at 7407b64481bc49ad552f9ba0ff2efe1f6fb0982e, but e6d9a30c889fe042cf3ad5073519f348dbe924f0 is also affected. Prior versions do not support Basic authentication. Apache is at 2.4.10-9 (Debian 8/Jessie).

**Comment by simo5** [comment]
On Tue, 2015-03-10 at 04:30 -0700, Dennis Schridde wrote:
> When I try to login to my webserver from a non-Kerberos enabled
> browser (machine does NOT use Kerberos authentication and
> `network.negotiate-auth.trusted-uris` is NOT set in Firefox),
> authentication fails and I see following error message in the server
> logs:
> ```
> [auth_gssapi:error] … gss_init_sec_context() failed: [Unspecified GSS
> failure.  Minor code may provide more information (Ticket expired)]
> ```
> 
> Initially I also got:
> ```
> [auth_gssapi:error] … In Basic Auth, gss_acquire_cred_with_password()
> failed: [Unspecified GSS failure.  Minor code may provide more
> information (Principal in credential cache does not match desired
> name)]
> ```
> This message currently does not appear, but I have seen it a long time
> ago already. So it seems to show up randomly?

Can you try to add:
GssapiCredStore ccache:MEMORY:user_ccache

And see if this makes things work better ?

I think there may be some issue with the ccache when multiple users are
authenticating, that I have no considered. I will investigate and
provide a better patch shortly.

> Login using a Kerberos enabled browser (i.e. machine uses Kerberos
> authentication and `network.negotiate-auth.trusted-uris` is set in
> Firefox) succeeds, so this seems to affect only Basic authentication.
> 
> I use following Apache config:
> ```apache
>                 <Location /auth/login/RemoteUser:self>
>                         AuthName "???"
>                         AuthType GSSAPI
> 
>                         GssapiBasicAuth On
>                         GssapiCredStore
> keytab:/etc/apache2/http.keytab
> 
> #                       GssapiConnectionBound On
> #                       Header set Persistent-Auth "true"
> 
> #                       GssapiUseSessions On
> #                       Session On
> #                       SessionCookieName gssapi_session
> path=/;httponly;secure;
> 
>                         Require valid-user
>                 </Location>
> ```
> 
> The commented out parts were in use (and the client also authenticated
> several times during the time they were enabled), but to limit the
> testcase I removed them for now.
> 
> The machine's clock is synchronised via NTP and I checked that the
> time is correct.
> 
> I am currently at 7407b64481bc49ad552f9ba0ff2efe1f6fb0982e, but
> e6d9a30c889fe042cf3ad5073519f348dbe924f0 is also affected. Prior
> versions do not support Basic authentication. Apache is at 2.4.10-9
> (Debian 8/Jessie).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/modauthgssapi/mod_auth_gssapi/issues/11


-- 
Simo Sorce * Red Hat, Inc * New York

**Comment by devurandom** [comment]
I still get:
```
[auth_gssapi:error] … gss_init_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Ticket expired)]
```

Config is now:
```
                <Location /auth/login/RemoteUser:self>
                        AuthName "Phabricator project management"

#                       AuthType Kerberos
#
#                       Krb5Keytab /etc/apache2/http.keytab

                        AuthType GSSAPI

                        GssapiCredStore keytab:/etc/apache2/http.keytab
                        GssapiCredStore ccache:MEMORY:user_ccache

                        GssapiBasicAuth On

                        GssapiConnectionBound On
                        Header set Persistent-Auth "true"

                        GssapiUseSessions On
                        Session On
                        SessionCookieName gssapi_session path=/;httponly;secure;

                        Require valid-user
                </Location>
```

**Comment by simo5** [comment]
On Tue, 2015-03-10 at 06:53 -0700, Dennis Schridde wrote:
> I still get:
> ```
> [auth_gssapi:error] … gss_init_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Ticket expired)]
> ```
> 
> Config is now:
> ```
>                 <Location /auth/login/RemoteUser:self>
>                         AuthName "Phabricator project management"
> 
> #                       AuthType Kerberos
> #
> #                       Krb5Keytab /etc/apache2/http.keytab
> 
>                         AuthType GSSAPI
> 
>                         GssapiCredStore keytab:/etc/apache2/http.keytab
>                         GssapiCredStore ccache:MEMORY:user_ccache
> 
>                         GssapiBasicAuth On
> 
>                         GssapiConnectionBound On
>                         Header set Persistent-Auth "true"
> 
>                         GssapiUseSessions On
>                         Session On
>                         SessionCookieName gssapi_session path=/;httponly;secure;
> 
>                         Require valid-user
>                 </Location>
> ```

Ok, can you check if you have a ticket in pache's ccache ?

I assume debian still defaults to FILE ccache and does not use
private /tmp so you should be able to
klist -kt /tmp/krb5cc_<apache's user id here>

Does it show you an expire ticket ?

Simo.

**Comment by devurandom** [comment]
See my last comment:
> I also noticed that the file `/tmp/krb5cc_33` (uid 33 is www-data, which is the user apache runs as) contains only expired tickets, including the TGT.

**Comment by simo5** [comment]
Upon further testing, I see a crash with this code, reopening

**Comment by devurandom** [comment]
Out of curiosity (and without knowing much about GSSAPI and just basics about Kerberos): Shouldn't the GSSAPI library renew or request a TGT if the current one is expired or none exists at all? And if the host/service tickets are expired or missing, shouldn't it do the same? Automatically?

**Comment by simo5** [comment]
It should, but it doesn't in this case, which I think is a bug, but we need to avoid using the default ccache anyway (which could be seen as a bug in gss_acquire_cred_with_password too) so I am just killing 2 birds with a stone :)

**Comment by devurandom** [comment]
> It should, but it doesn't in this case, which I think is a bug, but we need to avoid using the default ccache anyway (which could be seen as a bug in gss_acquire_cred_with_password too) so I am just killing 2 birds with a stone :)

Are there upstream bugreports for these two bugs?

**Comment by simo5** [comment]
On Tue, 2015-03-10 at 14:49 -0700, Dennis Schridde wrote:
> > It should, but it doesn't in this case, which I think is a bug, but we need to avoid using the default ccache anyway (which could be seen as a bug in gss_acquire_cred_with_password too) so I am just killing 2 birds with a stone :)
> 
> Are there upstream bugreports for these two bugs?

This is one:
http://krbdev.mit.edu/rt/Ticket/Display.html?id=8152

We are discussing with upstream a number of other issues with this
interface, meanwhile I would love to know if the patches I posted
completely fix your issues.

Simo.

**Comment by devurandom** [comment]
I am using v1.1.0 now, which appears to work. Thanks!

**Comment by devurandom** [comment]
P.S: Is it possible to subscribe to that MIT-Kerberos bugreport?
