### ISSUE TITLE
PersistentAuth is not sent on 3xx responses

### ISSUE THREAD

**Issue by michael-o** [modauthgssapi/mod_auth_gssapi#110]
I have enabled the following:

    GssapiConnectionBound On
    GssapiSignalPersistentAuth On

This is the fired request: `curl -L --verbose --negotiate -u : "http://example.com/~osipovmi/protected/tdm"`

The output says:

    * Hostname was NOT found in DNS cache
    *   Trying 1.2.3.4...
    * Connected to example.com (1.2.3.4) port 80 (#0)
    > GET /~osipovmi/protected/tdm HTTP/1.1^M
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 401 Unauthorized^M
    < Date: Mon, 10 Oct 2016 19:58:29 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < WWW-Authenticate: Negotiate^M
    < Content-Length: 532^M
    < Content-Type: text/html; charset=iso-8859-1^M
    < ^M
    * Ignoring the response-body
    * Connection #0 to host example.com left intact
    * Issue another request to this URL: 'http://example.com/~osipovmi/protected/tdm'
    * Found bundle for host example.com: 0x40059810
    * Re-using existing connection! (#0) with host example.com
    * Connected to example.com (1.2.3.4) port 80 (#0)
    * Server auth using Negotiate with user ''
    > GET /~osipovmi/protected/tdm HTTP/1.1^M
    > Authorization: Negotiate YIIPkAYGKwYBBQUCoI...
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 301 Moved Permanently^M
    < Date: Mon, 10 Oct 2016 19:58:29 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < WWW-Authenticate: Negotiate oYGzMIGwoAMKAQChC...
    < Location: http://example.com/~osipovmi/protected/tdm/^M
    < Content-Length: 417^M
    < Content-Type: text/html; charset=iso-8859-1^M
    < ^M
    * Ignoring the response-body
    * Connection #0 to host example.com left intact
    * Issue another request to this URL: 'http://example.com/~osipovmi/protected/tdm/'
    * Found bundle for host example.com: 0x40059810
    * Re-using existing connection! (#0) with host example.com
    * Connected to example.com (1.2.3.4) port 80 (#0)
    > GET /~osipovmi/protected/tdm/ HTTP/1.1^M
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 200 OK^M
    < Date: Mon, 10 Oct 2016 19:58:29 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < Content-Length: 662^M
    < Content-Type: text/html;charset=ISO-8859-1^M
    < ^M
    * Connection #0 to host example.com left intact

With the 301, the connection is authenticated and subsequent requests are fine but the `Persistent-Auth` header is completely missing. In contrast, let's avoid the redirect: ` curl --verbose --negotiate -u : "http://example.com/~osipovmi/protected/tdm/"`

and the output is:

    * Hostname was NOT found in DNS cache
    *   Trying 1.2.3.4...
    * Connected to example.com (1.2.3.4) port 80 (#0)
    > GET /~osipovmi/protected/tdm/ HTTP/1.1^M
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 401 Unauthorized^M
    < Date: Mon, 10 Oct 2016 20:05:55 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < WWW-Authenticate: Negotiate^M
    < Content-Length: 532^M
    < Content-Type: text/html; charset=iso-8859-1^M
    < ^M
    * Ignoring the response-body
    * Connection #0 to host example.com left intact
    * Issue another request to this URL: 'http://example.com/~osipovmi/protected/tdm/'
    * Found bundle for host example.com: 0x40059810
    * Re-using existing connection! (#0) with host example.com
    * Connected to example.com (1.2.3.4) port 80 (#0)
    * Server auth using Negotiate with user ''
    > GET /~osipovmi/protected/tdm/ HTTP/1.1^M
    > Authorization: Negotiate YIIPkAYGKwYBBQ...U
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 200 OK^M
    < Date: Mon, 10 Oct 2016 20:05:55 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < WWW-Authenticate: Negotiate oYGzMIGwoAMKA...
    < Persistent-Auth: true^M
    < Content-Length: 662^M
    < Content-Type: text/html;charset=ISO-8859-1^M
    < ^M
    * Connection #0 to host example.com left intact

Something is fishy about that...

**Comment by simo5** [comment]
Do you get any error in the apache log when the 301 is returned ?
Also what version of mod_auth_gssapi are you using ?

**Comment by simo5** [comment]
NVM, the header says 1.4.1, still I'd like to jknoe if you see any errors from apache, you may also want to raise debug level to see if there is any message that gives a clue as to why the header would be missing.

**Comment by michael-o** [comment]
It indeed does:

     AH01630: client denied by server configuration: /net/home/osipovmi/public_html/protected/tdm/.htaccess

though I have `Require user osipovmi@EXAMPLE.COM` and module configuration happens in the parent directory.

The `userdir` directive says:

    <Directory "/net/home/*/public_html">
        AllowOverride FileInfo AuthConfig Limit Indexes
        Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
        Require method HEAD GET POST OPTIONS
        Require all granted
    </Directory>

Here is the debug log:

    [Mon Oct 10 22:36:03.184743 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.184763 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.201834 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.201860 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.270322 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: granted
    [Mon Oct 10 22:36:03.270337 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: granted
    [Mon Oct 10 22:36:03.270350 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.
    [Mon Oct 10 22:36:03.274141 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.274157 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.274166 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(887): [client <IP>:61400] Already established context found!
    [Mon Oct 10 22:36:03.274180 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: granted
    [Mon Oct 10 22:36:03.274188 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: granted
    [Mon Oct 10 22:36:03.274200 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.
    [Mon Oct 10 22:36:03.275768 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.275782 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
    [Mon Oct 10 22:36:03.275794 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require user osipovmi@EXAMPLE.COM: granted
    [Mon Oct 10 22:36:03.275804 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: granted
    [Mon Oct 10 22:36:03.276978 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.
    [Mon Oct 10 22:36:03.278511 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of Require all denied: denied
    [Mon Oct 10 22:36:03.278530 2016] [authz_core:debug] [pid 1349] mod_authz_core.c(809): [client <IP>:61400] AH01626: authorization result of <RequireAny>: denied
    [Mon Oct 10 22:36:03.278537 2016] [authz_core:error] [pid 1349] [client <IP>:61400] AH01630: client denied by server configuration: /net/home/osipovmi/public_html/protected/tdm/.htaccess
    [Mon Oct 10 22:36:03.279058 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.
    [Mon Oct 10 22:36:03.279574 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.
    [Mon Oct 10 22:36:03.280146 2016] [auth_gssapi:debug] [pid 1349] mod_auth_gssapi.c(656): [client <IP>:61400] GSSapiImpersonate not On, skipping impersonation.

and the request log:

    <IP> - - [10/Oct/2016:22:36:03 +0200] "GET /~osipovmi/protected/tdm HTTP/1.1" 401 532
    <IP> - osipovmi@EXAMPLE.COM [10/Oct/2016:22:36:03 +0200] "GET /~osipovmi/protected/tdm HTTP/1.1" 301 417
    <IP> - osipovmi@EXAMPLE.COM [10/Oct/2016:22:36:03 +0200] "GET /~osipovmi/protected/tdm/ HTTP/1.1" 200 662

**Comment by frenche** [comment]
This is strange, the final negotiate header is returned so the persistent-auth header should too.
The only difference I see is one is set with apr_table_set and the other with apr_table_add, but it shouldn't matter (I think).

How do you set the redirect? via an apache directive?

**Comment by michael-o** [comment]
@frenche I do not send the header myself. `tdm` is a directory in my `public_html`. Apache does it by itself. I guess this is done by  [`DirectorySlash`](https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryslash).

**Comment by frenche** [comment]
Ah silly me, there is a more significant difference between the final negotiate header and the persist-auth header, while the negotiate header is added to 'req->err_headers_out' table the persist-auth header is set in 'req->headers_out' table.
Perhaps that's why Simo asked if you see any errors, though perhaps apache considers 3xx response as an error and would not send out the 'headers_out' headers.

**Comment by michael-o** [comment]
@frenche This would be a good explanation but 3xx aren't errors. I have made so digging and found this [old thread](http://mason-users.narkive.com/iMw6m7z8/headers-problem-and-redirect) about it as well as [this documentation](http://docstore.mik.ua/orelly/apache_mod/106.htm): `err_headers_out()` and `headers_out`. Finally the [official documentation](https://ci.apache.org/projects/httpd/trunk/doxygen/structrequest__rec.html#a9f49c2d5680987c0c28466ea37d41a62):

> MIME header environment for the response, printed even on errors and persist across internal redirects

Seems like `Persistent-Auth` must be handled just like `WWW-Authenticate` completion token.

**Comment by frenche** [comment]
> Seems like Persistent-Auth must be handled just like WWW-Authenticate completion token.

Yea, once we authenticated the connection we should send the persist-auth header.
Can you try to change header_out to err_header_out at mod_auth_gssapi.c:1052
If it works, feel free to open a pull request :)

**Comment by michael-o** [comment]
@frenche I will retry with a patch version and provide a PR.

**Comment by michael-o** [comment]
Locally patched:

    * Hostname was NOT found in DNS cache
    *   Trying 1.2.3.4...
    * Connected to example.com (1.2.3.4) port 80 (#0)
    > GET /~osipovmi/protected/tdm HTTP/1.1^M
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 401 Unauthorized^M
    < Date: Tue, 11 Oct 2016 11:50:43 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < WWW-Authenticate: Negotiate^M
    < Content-Length: 532^M
    < Content-Type: text/html; charset=iso-8859-1^M
    < ^M
    * Ignoring the response-body
    * Connection #0 to host example.com left intact
    * Issue another request to this URL: 'http://example.com/~osipovmi/protected/tdm'
    * Found bundle for host example.com: 0x40059810
    * Re-using existing connection! (#0) with host example.com
    * Connected to example.com (1.2.3.4) port 80 (#0)
    * Server auth using Negotiate with user ''
    > GET /~osipovmi/protected/tdm HTTP/1.1^M
    > Authorization: Negotiate YIIPkAYGKwYBB...
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 301 Moved Permanently^M
    < Date: Tue, 11 Oct 2016 11:50:43 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < Persistent-Auth: true^M
    < WWW-Authenticate: Negotiate oYGzMIGwoAMKA...
    < Location: http://example.com/~osipovmi/protected/tdm/^M
    < Content-Length: 417^M
    < Content-Type: text/html; charset=iso-8859-1^M
    < ^M
    * Ignoring the response-body
    * Connection #0 to host example.com left intact
    * Issue another request to this URL: 'http://example.com/~osipovmi/protected/tdm/'
    * Found bundle for host example.com: 0x40059810
    * Re-using existing connection! (#0) with host example.com
    * Connected to example.com (1.2.3.4) port 80 (#0)
    > GET /~osipovmi/protected/tdm/ HTTP/1.1^M
    > User-Agent: curl/7.39.0^M
    > Host: example.com^M
    > Accept: */*^M
    > ^M
    < HTTP/1.1 200 OK^M
    < Date: Tue, 11 Oct 2016 11:50:43 GMT^M
    < Server: Apache/2.4.23 (FreeBSD) OpenSSL/1.0.2j PHP/5.6.26 SVN/1.9.4 mod_auth_gssapi/1.4.1^M
    < Content-Length: 662^M
    < Content-Type: text/html;charset=ISO-8859-1^M
    < ^M
    * Connection #0 to host example.com left intact

PR is underway!

**Comment by michael-o** [comment]
@frenche PR has landed.
