### ISSUE TITLE
Broken ccache name when "GssapiDelegCcacheUnique Off"

### ISSUE THREAD

**Issue by linuxrrze** [modauthgssapi/mod_auth_gssapi#115]
I was observing regular GSSAPI errors when using mod_auth_gssapi.
Apache log reported random strings after the ccache path name (in about 1 of 4 GSSAPI accesses).

Something like:
       /tmp/\x7f
while most of the time it was using the correct:
       /tmp/marcel@MYDOMAIN.DE

Further investigation shows, that the error seemed to occur only if 
    "GssapiDelegCcacheUnique Off"
is used (also seems to be default setting).

Looking into the code I found that different calls are used for different GssapiDelegCcacheUnique settings:

Off: apr_psprintf(req->pool, "%s/%s", dir, escaped);
On: apr_psprintf(mc->pool, "%s/%s", dir, escaped);

So I replaced "req" with "mc" (in the "use_unique == false" code tree) and things started to work.
I'm not familiar with apache module programming, so this might not be the right way to fix things.
My tests however look very promising after this change.

Here's the simple diff:

diff --git a/src/mod_auth_gssapi.c b/src/mod_auth_gssapi.c
index c3f258b..8a9ca7f 100644
--- a/src/mod_auth_gssapi.c
+++ b/src/mod_auth_gssapi.c
@@ -216,7 +216,7 @@ static char *get_ccache_name(request_rec *req, char *dir, const char *gss_name,
     escaped = escape(req->pool, escaped, '/', "~");
 
     if (use_unique == false) {
-        return apr_psprintf(req->pool, "%s/%s", dir, escaped);
+        return apr_psprintf(mc->pool, "%s/%s", dir, escaped);
     }
 
     ccname = apr_psprintf(mc->pool, "%s/%s-XXXXXX", dir, escaped);

**Comment by frozencemetery** [comment]
I admit to touching this last (6a0bc4f5)

The old behavior (i.e., pre-unique ccaches) had `req->pool` there, which has been preserved.  I think that `mc->pool` is probably more correct, since it's what the newer, unique-ccache path does.  Either way it's a problem that both paths don't have the same lifetime.

What do you think, @simo5?

**Comment by frenche** [comment]
Which apache logs exactly, could you post them?
Basically, the difference between the two statements would determine the lifespan of the allocated string, req's pool is destructed by apache as soon as the request is handled, while mc's pool is cleaned up only with the connection pool is (longer).
So it sounds like we might be accessing deallocated memory.

**Comment by linuxrrze** [comment]
Errors were noted in the apache error log.
Here's some examples:

[Wed Dec 14 17:26:18.348251 2016] [:error] [pid 25128] [client IPV6ADDRESS:45482] KRB5CCNAME file (/tmp/\\/(h*\xa0\x96\x9f\x7f) lookup failed!, referer: https://mail.mydomain.de/skins/larry/styles.min.css?s=1480262870
[Wed Dec 14 17:26:18.357101 2016] [:error] [pid 25128] [client IPV6ADDRESS:45482] KRB5CCNAME file (/tmp/\x7f) lookup failed!, referer: https://mail.mydomain.de/skins/larry/styles.min.css?s=1480262870
[Wed Dec 14 17:26:18.357319 2016] [:error] [pid 15910] [client IPV6ADDRESS:45488] KRB5CCNAME file (/tmp/\x81\xe3\x119\x01\xee_\xf5.\xc5N\xadEE\xdc\xc2ZK\xac\x8cn\x07C\x82\x15\xc61\x8fF\n\tX\x11\x0f27\xae\xec,V\xcf<9\x97*\x9b\x86\x96C\xf6\x02_\x83\x98\xcf\x07\x14\xd3\x17\xef\x8b\x1e\xca\xc5\x1a\x97\xbf\xc3A\xea\xac.V0\xba\x9b\xe1\xce\xe1\x87\xb5\x1b\xfb\xf6$]\xcfjw\xde_F~>\x1a\x86F\xa7\xcc\x9fX\x8e\xf9\x1bG\xd7\xa8b\xcep\x16\x99\xd6\x1cO\xa6\x9f\xbb\xd6D\x7fvzNB\xb4\x8d\xaef\xa8\xf8\x7f\xe0\xb7\xff\x97L\x89\xc8\xd582#\x7f\xf5\xbdL\x0c\xcc\xf4\xd0\xb3\xc0\xf1\xd9\xe4\x13\x8b\x91xk\x12\xbf5U\xdc\xbf\xf9\xcdH\xad\xf6\xef\xfb\xfe\xc9?\xdc\x91\xe4S\xf6\xd5\xc7\x8a\xdd\xbf>\xf9\xb6\xcf5N\\\x01$=.U-M:\xab\x86Qe\xfb\x92\xe3\x0en\xdb\x1c\x99(\xab\x03;\x99e\xd2\xb5\x17\x9a\x8ax;\xcenEz\x85\x91~j-\xb7{\xf8\xa5\xacL\xabc\x95\x85\xdfI\xe3\xb4\xf6\xe9\x8f[\x7f\xea\xaf\xda\xfa\xad_\x01\xea\xfc\x96\xac\x7f*\x8b\xbc`Ku:\xbb|\xe4U<\xe2\xfc\xebv\xe9\xb0M\xab\xba\xca!Z\xe6\x04\x8e\xa2z\xb5\xf1\xab\xfb\x89\xfbMx\xac\xfca\xa1\x81,\xdcX\x90\x9f*w\xe8q\xfd\xd2ek\xa0\x1b\xe1\xfd\xf9\xbd\xde\x19\xea\x84\x13\xf3\x0f\xce\xef\xf7\xde\xbf\xfa\xd9\xe6y\xd9\xe2\x8b\xd8\xc4\xe6\xe7\xc6\x98\x17(\xe48qFHf\x8a\x88\xe5~W{U^%\xd3S\xa1-u\x1f\x13\xb0\xeb\x1e\xf8\x9e\xdb\x1d\x11\r\xf3\xb3\x18\xf2\xafq\xee\x0f\xcaR(\xf4]\xab$"\xb0\xa5\x84oa\\\xa3K\xae) lookup failed!, referer: https://mail.mydomain.de/plugins/jqueryui/themes/larry/jquery-ui-1.10.4.custom.css?s=1480262870
[Wed Dec 14 17:27:30.926293 2016] [:error] [pid 15968] [client IPV6ADDRESS:45566] KRB5CCNAME file (/tmp/V) lookup failed!, referer: https://mail.mydomain.de/?_task=mail&_mbox=Mailing-Lists%2Fsamba-technical

**Comment by frenche** [comment]
Ok, the resulted string (ccache_path) ends up being saved on mc->ccname, so it should be allocated on mc's pool anyway.
Not sure how exactly the error occurs, but mag_set_req_data() is called from more than one place, so it's possible in your case it is called after the original request was already cleaned up.
Long story short, your fix looks good to me too (maybe you can do a pull request?).

**Comment by linuxrrze** [comment]
I'll do so (once I figured out how to do a pull request).

Hints welcome ;-)
