### ISSUE TITLE
Delegation - GssapiDelegCcacheDir - failed to store delegated creds

### ISSUE THREAD

**Issue by n2five6** [modauthgssapi/mod_auth_gssapi#122]
We have issues with ticket delegation on CentOS 7.2 - we want to run external command in PHP with delegated ticket (i.e. smbclient). Authentication works well, also Username is visible in the log files of Apache. 

**Apache-Directory-Config:**

> AuthName                        "Kerberos Authentication"
> AuthType                        GSSAPI
> GssapiCredStore                 keytab:/etc/httpd/krb5.keytab
> GssapiBasicAuth On
> GssapiBasicAuthMech krb5
> GssapiSSLonly Off
> GssapiConnectionBound On
> GssapiCredStore                 ccache:/var/tmp/httpd_krb5_ccache
> GssapiDelegCcacheDir            /var/tmp/clientcaches
> GssapiLocalName on

**Directory permissions:**

> [root@XXXX]# pwd
> /var/tmp
> [root@XXXX]# ls -l
> total 44
drwx------. 2 apache apache  4096 Feb  1 11:39 clientcaches
drwxr-xr-x. 2 apache apache  4096 Feb  1 11:13 httpd_krb5_ccache

**Keytab:**

> [root@XXXX httpd]# ls -l
> total 16
> drwxr-xr-x. 2 root root 4096 Feb  1  2017 conf
> drwxr-xr-x. 2 root root 4096 Feb  1 12:58 conf.d
> drwxr-xr-x. 2 root root 4096 Feb  1 10:06 conf.modules.d
> -rw-r--r--. 1 root root  422 Feb  1 10:23 krb5.keytab
> lrwxrwxrwx. 1 root root   19 Feb  1  2017 logs -> ../../var/log/httpd
> lrwxrwxrwx. 1 root root   29 Feb  1  2017 modules -> ../../usr/lib64/httpd/modules
> lrwxrwxrwx. 1 root root   10 Feb  1  2017 run -> /run/httpd

**Gssapi-Version:**

> [root@XXXX httpd]# yum info mod_auth_gssapi
> Loaded plugins: etckeeper, fastestmirror
> Loading mirror speeds from cached hostfile
> Installed Packages
> Name        : mod_auth_gssapi
> Arch        : x86_64
> Version     : 1.4.0
> Release     : 1.el7
> Size        : 134 k
> Repo        : installed
> From repo   : base
> Summary     : A GSSAPI Authentication module for Apache
> URL         : https://github.com/modauthgssapi/mod_auth_gssapi
> License     : MIT
> Description : The mod_auth_gssapi module is an authentication service that implements the
>             : SPNEGO based HTTP Authentication protocol defined in RFC4559.

**Apache-Error-Log-File:**

> [Wed Feb 01 12:59:49.354622 2017] [auth_gssapi:error] [pid 3359] [client XX.XXX.X.XX:58613] failed to store delegated creds: [Unspecified GSS failure.  Minor code may provide more information (No credentials cache found)]
> [Wed Feb 01 12:59:49.354758 2017] [:error] [pid 3359] [client XX.XXX.X.XX:58613] KRB5CCNAME file (/var/tmp/clientcaches/USER@DOMAIN) lookup failed!

XX.XXX.X.XX = Client IP
USER@DOMAIN = Correct user and domain

**PHP-Server-Var:**
>  ["KRB5CCNAME"]=>  string(52) "FILE:/var/tmp/clientcaches/USER@DOMAIN"

**Comment by amessina** [comment]
This looks similar to my issue in #69.

**Comment by simo5** [comment]
If mod_auth_gssapi sets KRB5CCNAME it means it created the ccache file, but it may have done that in a previous request if you use GssapiConnectionBound, does your PHP application delete the ccache after the request is done by chance ?

P.S: your keytab is world-writable so it is compromised, I'd rotate it and make sure it is readable only by apache, or better yet use gss-proxy and have it readable only by root.

**Comment by n2five6** [comment]
No, PHP-App will not delete any file or cache.

After run that PHP-Script there is no file in /var/tmp/clientcaches/ - also if we run a readdir in the PHP-Script. Keytab is read/write to root and read-only to all others. We tried some permission configuration to check if there is the problem (clientcache folder). As we started we have done this without the connectionbound option (we allow anyway only krb5 -> GssapiBasicAuthMech krb5).

For me it looks like that the file can't be created.

**Comment by simo5** [comment]
Can you write to /var/tmp/clientcaches/ as the apache user ?

**Comment by simo5** [comment]
@amessina might be

**Comment by n2five6** [comment]
I checked it, the clientcaches will be created but the ccache not.

**Comment by n2five6** [comment]
Is there anything to do, that the ccache will be created?

**Comment by frenche** [comment]
Can you show the output of 'klist -c clientcaches/user@REALM', or try to use it manually.
What way the client authenticate to httpd? Basic auth? or SPNEGO?

**Comment by n2five6** [comment]
Looks like it is empty:

> [root@XXXX ~]# klist -c /var/tmp/clientcaches/USER@DOMAIN
> klist: Bad format in credentials cache (filename: /var/tmp/clientcaches/USER@DOMAIN)
> [root@XXXX ~]# cat /var/tmp/clientcachesUSER@DOMAIN
> [root@XXXX ~]#

**Comment by simo5** [comment]
If you remove that empty file, and re-authenticate, will a good one be created ?
Or do you get again an empty file ?

**Comment by n2five6** [comment]
@simo5 No. Also empty.

**Comment by simo5** [comment]
libgssapi never creates empty ccache files, so I am at a loss to know what's going on.
Can you replicate this when protcting a normal static file instead of a PHP application ?

**Comment by n2five6** [comment]
I removed this file an restared apache.
Since that, I don't see any file anymore in this directory - not before refresh the Webseite (vHost) and also not after that.

**I get still the error:**
> [Tue Feb 07 13:26:19.203776 2017] [auth_gssapi:error] [pid 16068] [client 10.102.0.1:50340] failed to store delegated creds: [Unspecified GSS failure.  Minor code may provide more information (No credentials cache found)]
> [Tue Feb 07 13:26:19.203856 2017] [:error] [pid 16068] [client 10.102.0.1:50340] KRB5CCNAME file (/var/tmp/clientcaches/USER@DOMAIN) lookup failed!

**PHP $_SERVER:**
> array(38) {
>   ["UNIQUE_ID"]=>
>   string(27) "WJm83dG8Ymz0ZifIU62l2QAAAAI"
>   ["GSS_NAME"]=>
>   string(25) "nschillinger@DS1.INTERNAL"
>   ["GSS_SESSION_EXPIRATION"]=>
>   string(10) "1486504654"
>   ["KRB5CCNAME"]=>
>   string(52) "FILE:/var/tmp/clientcaches/USER@DOMAIN"
>   ["HTTP_HOST"]=>
>   string(27) "bauteildb.vie.at.tttech.ttt"
>   ["HTTP_CONNECTION"]=>
>   string(10) "keep-alive"
> ...
> }

**Apache-Conf:**

> <Directory "/var/www/html/XXX/">
> 	AllowOverride All
> 	Options Indexes FollowSymLinks
> 	AuthName	 "Kerberos Authentication"
> 	AuthType	 GSSAPI
> 	GssapiCredStore	 keytab:/etc/httpd/krb5.keytab
> 	GssapiBasicAuth On
> 	GssapiBasicAuthMech krb5
> 	GssapiSSLonly Off
> 	GssapiCredStore	 ccache:FILE:/var/tmp/httpd_krb5_ccache/krb5_ccache
> 	GssapiDelegCcacheDir		 /var/tmp/clientcaches
> 	GssapiLocalName on
> 	GssapiNegotiateOnce on
> 	Require valid-user
> </Directory>

**Folder is also write able for apache:**
> [root@XXXX~]# cd /var/tmp/clientcaches/
> [root@XXXX clientcaches]# su apache -s /bin/bash
> bash-4.2$ pwd
> /var/tmp/clientcaches
> bash-4.2$ touch test
> bash-4.2$ ls -la
> total 8
> drwx------. 2 apache apache 4096 Feb  7 13:33 .
> drwxrwxrwt. 9 root   root   4096 Feb  7 13:25 ..
> -rw-r--r--. 1 apache apache    0 Feb  7 13:33 test
> 
>

**Comment by simo5** [comment]
Can you add KRB5_TRACE=/var/tmp/apache.krb5.trace to the env vars set up by your init script/unit file and repeat ?
Hopefully the file will contain clues about why it fails to create the ccache file

**Comment by n2five6** [comment]
We entered the KRB5_TRACE to /etc/sysconfig/httpd:

> LANG=C
> KRB5_TRACE=/var/tmp/apache.krb5.trace

 And checked after apache restart the  /proc/17621/environ:

> LANG=C^@PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin^@NOTIFY_SOCKET=/run/systemd/notify^@KRB5_TRACE=/var/tmp/apache.krb5.trace^@

But no file will be generated:

> [root@bauteildb sysconfig]# ls -la /var/tmp/
> drwxrwxrwt.  9 root   root    4096 Feb  8 09:44 .
> drwxr-xr-x. 21 root   root    4096 Feb  1 11:01 ..
> drwx------.  2 apache apache  4096 Feb  7 13:33 clientcaches
> -rw-------.  1 root   root    2421 Feb  8 09:31 host_0
> drwxr-----.  2 apache apache  4096 Feb  1 11:13 httpd_krb5_ccache
> drwx------.  2 root   root   16384 Oct 12 19:03 lost+found

Do we need to set parameters like "kinit"?
=> https://web.mit.edu/kerberos/krb5-1.12/doc/admin/env_variables.html

**Comment by n2five6** [comment]
We still having the same issues - also with the new version "mod_auth_gssapi-1.5.0-1.fc25.x86_64".
In that moment when we add the line: `GssapiDelegCcacheDir /var/run/httpd/clientcaches` GSSAPI stops working.

Without restrictions to the auth mechnanism:

```
[Mon Aug 07 10:50:57.300244 2017] [auth_gssapi:error] [pid 39489] [client XX.XX.XX.XX:59406] 
gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information ( SPNEGO cannot find mechanisms to negotiate)]
```

With krb5:

```
[Mon Aug 07 13:10:12.187105 2017] [auth_gssapi:error] [pid 1397] [client XX.XX.XX.XX:60893] gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information (Bad format in credentials cache (filename: /var/run/httpd/krb5ccache))]
```


Current Config:
```
LogLevel Debug

AuthName                        "IT WebServices Kerberos Authentication"
AuthType                        GSSAPI
GssapiCredStore                 keytab:/etc/httpd/krb5.keytab
GssapiBasicAuth                 On
GssapiBasicAuthMech             krb5
GssapiAllowedMech               krb5
GssapiSSLonly                   Off
GssapiConnectionBound           Off
GssapiLocalName                 on
GssapiNegotiateOnce             On

GssapiUseS4U2Proxy On
GssapiCredStore client_keytab:/etc/krb5.keytab
GssapiCredStore ccache:FILE:/var/run/httpd/krb5ccache
GssapiDelegCcacheDir /var/run/httpd/clientcaches

Require valid-user
```

Folder
```
[root@SRV~]# su apache -s /bin/bash
bash-4.2$ cd /var/run/httpd/
bash-4.2$ touch test
bash-4.2$ ls -l
total 11
-rw-r--r--. 1 root   root    8 Aug  7 13:10 authdigest_shm.40730
-rw-r--r--. 1 root   root    8 Jun 11 03:40 authdigest_shm.52779
drwxr-xr-x. 2 apache apache 40 Aug  4 14:49 clientcaches
drwx------. 2 apache apache 40 Mar 16 07:36 htcacheclean
-rw-r--r--. 1 root   root    6 Aug  7 13:10 httpd.pid
drwxr-----. 2 apache apache 40 Aug  4 14:50 krbcache
-rw-r--r--. 1 apache apache  0 Aug  7 13:18 test
bash-4.2$ rm test
bash-4.2$ cd clientcaches
bash-4.2$ touch test
bash-4.2$ ls -l
total 0
-rw-r--r--. 1 apache apache 0 Aug  7 13:19 test
bash-4.2$ rm test
bash-4.2$
```

**Comment by n2five6** [comment]
News:
When we enter User/Password on the Basic-Auth (that appear if we set the GssapiDelegCcacheDir) we are getting the KRB5CCNAME in the ENV-Vars. (same config as posted before).

Is there a limitation for the ticket size?

**Comment by simo5** [comment]
No there should be no limitation.
But your problem seems to be that /var/run/httpd/krb5ccache is a directory.
Dlete tht directory and apache will be able to obtain it's own creds in that "file".

**Comment by n2five6** [comment]
Amazing! Works now!
Many thanks for the support and the module!

**Comment by n2five6** [comment]
Sorry, to early. Two issued left ...

First: 
We get now the credential cache path, but only with basic auth.
If I enter the site, I will always prompted to enter username/password.

```
LogLevel Debug
AuthName        "IT WebServices Kerberos Authentication"
AuthType        GSSAPI
GssapiCredStore keytab:/etc/httpd/krb5.keytab
GssapiBasicAuth On
GssapiBasicAuthMech             krb5
GssapiAllowedMech               krb5
GssapiSSLonly   Off
GssapiConnectionBound           Off
GssapiLocalName on
GssapiNegotiateOnce             On
GssapiNameAttributes json

GssapiUseS4U2Proxy On
GssapiCredStore client_keytab:/etc/krb5.keytab
GssapiCredStore ccache:FILE:/var/run/httpd/krb5ccache
GssapiDelegCcacheDir /var/run/httpd/clientcaches

Require valid-user
AuthLDAPUrl     ldap://ldap.domain/dc=ds1,dc=internal?samAccountName
<RequireAll>
    <RequireAny>
        Require ldap-filter memberof:1.2.840.113556.1.4.1941:=cn=group,OU=permissions,OU=ttt,DC=ldap,DC=domain
    </RequireAny>
</RequireAll>
Options         FollowSymLinks
AllowOverride   All

```
Second: 
We also have troubles with PHP-LDAP and GSSAPI authentication.
The ENV-VAR KRB5CCNAME will be set correctly - also the file exists incl. correct permissions.
But we get each time if we run the script by HTTP-Request an error.

Script:
```
putenv('LDAPTLS_CACERT=/path/to/ca-bundle');
echo getenv("KRB5CCNAME "); // (Output: /var/run/httpd/clientcaches/user@ldap.domain)
$ldapconn = ldap_connect("ldaps://dc.ldap.domain",636);
ldap_set_option($ldapconn,LDAP_OPT_REFERRALS,0);
ldap_set_option($ldapconn,LDAP_OPT_PROTOCOL_VERSION,3);
ldap_sasl_bind($ldapconn, NULL, NULL, "GSSAPI");
echo ldap_error($ldapconn);  // (Output Local Error)
```

Apache Log-File:
```
Aug  8 11:24:21 SRV httpd: ldapdb_canonuser_plug_init() failed in sasl_canonuser_add_plugin(): invalid parameter supplied
Aug  8 11:24:21 SRV httpd: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No credentials cache found)
```

But if I start that Script manually it works:
```
su apache -s /bin/bash`
export KRB5CCNAME=/var/run/httpd/clientcaches/user@ldap.domain
php -f /path/to/script.php
```

**Comment by simo5** [comment]
KRB5CCNAME is not set as a process environment variable but as an apache server variable, you'll have to set your environment variable in php if you need to use it that way (beware of threaded servers stepping on each other this way)

If your browser is not doing "Negotiate" auth it means you have an issue on that side, either you do nto have credentials on the client or the browser is not configure to use them.
Also this: GssapiSSLonly   Off is not a good idea, some browsers may refise to perform (with some good reason) negotiate auth on unencrypted channels, and it is in genral a bad idea to use unencrypted communications.

Also do tno turn GssapiNegotiateOnce             On unless you have an actual issue with client browsers requireing it.

It seem these are all issues in configuration on your side, not bugs in mod_auth_gssapi, so, closing.

**Comment by n2five6** [comment]
We set it also as env var with setenv - but it did not work.
GssapiNegotiateOnce On is on, because we have issues with Users that comes from a foreign domain - (forced NTLM). The option GssapiSSLonly Off is set on our staging server - dont' worry.

If we disable the delegation in our config - SSO works well. We also test it with mod_auth_kerb on a different vHost - that works also with delegation - but with a very bad performance.

**Comment by amessina** [comment]
This seems like a similar result to what I had in #69.
