### ISSUE TITLE
Question about the use of realloc vs. memory pools

### ISSUE THREAD

**Issue by alejandro-perez** [modauthgssapi/mod_auth_gssapi#126]
Hello,

since I'm trying to get good knowledge of the GSS attribute exportation code, I've come across the use of realloc, which is surprising to me given that memory is usually allocated by means of apr_* functions and pools. Is not realloc using plain "malloc" underneath? If so, shouldn't the code use the pool?

I've seen two uses of realloc corresponding to the GSS attribute handling.
1) https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/mod_auth_gssapi.c#L1631-L1644
Here it seems that at least a cleanup fnc is registered, so memory should be freed.

2) https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/environ.c#L43-L51
In this case, I don't see any cleanup function. How is this memory freed?

**Comment by simo5** [comment]
On Thu, 2017-02-09 at 10:29 -0800, Alejandro Perez wrote:
> I've seen two uses of realloc corresponding to the GSS attribute
> handling.
> 
> 
> 
> https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/mod_
> auth_gssapi.c#L1631-L1644
> 
> Here it seems that at least a cleanup fnc is registered, so memory
> should be freed.

I think that this was done with realloc because there is no function to
free data with pools (as the assumption is that everything is freed
once you destroy the pool). That's why there is a cleanup function.
> 
> https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/envi
> ron.c#L43-L51
> 
> In this case, I don't see any cleanup function. How is this memory
> freed?
> 
> 
> 

This is probably a copy/paste bug, and the pool should be used.
Simo.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/modauthgs
> sapi/mod_auth_gssapi","title":"modauthgssapi/mod_auth_gssapi","subtit
> le":"GitHub repository","main_image_url":"https://cloud.githubusercon
> tent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/modauthgssapi/mod_auth_gssapi"}},"u
> pdates":{"snippets":[{"icon":"DESCRIPTION","message":"Question about
> the use of realloc vs. memory pools (#126)"}],"action":{"name":"View
> Issue","url":"https://github.com/modauthgssapi/mod_auth_gssapi/issues
> /126"}}}

**Comment by alejandro-perez** [comment]
> On Thu, 2017-02-09 at 10:29 -0800, Alejandro Perez wrote:
> > I've seen two uses of realloc corresponding to the GSS attribute
> > handling.
> >
> >
> >
> > https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/mod_
> > auth_gssapi.c#L1631-L1644
> >
> > Here it seems that at least a cleanup fnc is registered, so memory
> > should be freed.
>
> I think that this was done with realloc because there is no function to
> free data with pools (as the assumption is that everything is freed
> once you destroy the pool). That's why there is a cleanup function.

Makes sense.

> >
> > https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/envi
> > ron.c#L43-L51
> >
> > In this case, I don't see any cleanup function. How is this memory
> > freed?
> >
> >
> >
>
> This is probably a copy/paste bug, and the pool should be used.
> Simo.

I'm not sure about that. It uses realloc as in the example above to 
assure array grows in 16 modules. Maybe what it is missing is the 
cleanup function?

I can take care of that, if you want.

**Comment by simo5** [comment]
On Fri, 2017-02-10 at 03:16 -0800, Alejandro Perez wrote:
> I'm not sure about that. It uses realloc as in the example above to 
> assure array grows in 16 modules. Maybe what it is missing is the 
> cleanup function?

My reasoning was that mc has a well defined lifetime and it is probably
ok to "leak" some memory in it as it gets cleaned up relatively
quickly. However a cleanup function would work as well.

> I can take care of that, if you want.

Sure, thanks!

**Comment by alejandro-perez** [comment]
Fixed in #127
