### ISSUE TITLE
Login with Safari fails: gss_accept_sec_context() failed: [An unsupported mechanism was requested (Unknown error)]

### ISSUE THREAD

**Issue by devurandom** [modauthgssapi/mod_auth_gssapi#13]
A user of ours has an issue where he cannot login using his Safari browser.

He receives the message that authentication failed, while the server logs:
```
gss_accept_sec_context() failed: [An unsupported mechanism was requested (Unknown error)]
```

This happens with Safari 8.0.3 on Mac OS X 10.10.2 and iOS 8.2 as well:
```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
"Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4"
```

Our config is:
```
                        AuthType GSSAPI

                        GssapiCredStore keytab:/etc/apache2/http.keytab
                        GssapiCredStore ccache:MEMORY:user_ccache

                        GssapiBasicAuth On

                        GssapiConnectionBound On
                        Header set Persistent-Auth "true"

                        GssapiUseSessions On
                        Session On
                        SessionCookieName gssapi_session path=/;httponly;secure;
```

The same issue happens with mod-auth-kerb-5.4 (5.4-2.2 on Debian 8 "Jessie"), so this is probably not a bug in mod-auth-gssapi, but a misconfiguration. To fix it, I need your support.

P.S: Other browsers, like Chrome and Firefox on the same operating system (Mac OS X) are unaffected. These browsers are also known to be not affected on Linux (various distributions). I have not tested with IE or on Windows so far.

The service name is a CNAME for the server hostname. That hostname then resolves to an A record, which has a proper PTR reverse record setup.

**Comment by simo5** [comment]
If I had to guess it is possible Mac OS X is trying to fall back to NTLMSSP auth. If that is the case there isn't really much you can doi but return an error. You can try using gssntlmssp* but on the server side it is not really easy to use unless you have winbindd installed and a Windows Domain Controller.

* https://fedorahosted.org/gss-ntlmssp/

**Comment by devurandom** [comment]
Ok, I ran `make install` and manually installed the `mech.ntlmssp` file as `/etc/gss/mech.d/ntlmssp.conf`. Now the docs say I should set an environment variable pointing to a file with a password. Which password? Or is that the part that is unnecessary, if the server is running winbind and is a member of an Active Directory domain? I.e. should the rest work automatic with this setup?

**Comment by simo5** [comment]
If you have winbindd on the system it should just work now.

**Comment by devurandom** [comment]
Yes, I just got a confirmation from the user. Thanks!
