### ISSUE TITLE
mod_auth_gssapi fails to renew expired server credential under gssproxy

### ISSUE THREAD

**Issue by abbra** [modauthgssapi/mod_auth_gssapi#133]
When using FreeIPA git master with privilege separation where gssproxy is used to handle server's keytab access, mod_auth_gssapi fails to handle credential renewal.

Following is what can be seen in the httpd error_log:
<pre>
[Mon Mar 13 09:27:08.330819 2017] [auth_gssapi:error] [pid 7314] [client some-client:53104] gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information ( SPNEGO cannot find mechanisms to negotiate)], referer: https://ipa.example.com/ipa/xml
</pre>

and gssproxy logs say following:
<pre>
Mar 13 09:27:08 ipa.example.com gssproxy[3886]: [2017/03/13 08:27:08]: gp_rpc_execute: executing 6 (GSSX_ACQUIRE_CRED) for service "ipa-httpd", euid: 48,socket: (null)
Mar 13 09:27:08 ipa.example.com gssproxy[3886]:     GSSX_ARG_ACQUIRE_CRED( call_ctx: { "" [  ] } input_cred_handle: { "HTTP/ipa.example.com@EXAMPLE.COM" [ { "HTTP/ipa.example.com@EXAMPLE.COM" { 1 2 840 113554 1 2 2 } BOTH 86400 86400 } ] [ p9m....4...P..j3... ] 0 } add_cred: 0 desired_name: <Null> time_req: 4294967295 desired_mechs: { { 1 2 840 113554 1 2 2 } } cred_usage: BOTH initiator_time_req: 0 acceptor_time_req: 0 )
Mar 13 09:27:08 ipa.example.com gssproxy[3886]: gssproxy[3887]: (OID: { 1 2 840 113554 1 2 2 }) The referenced credential has expired, Unknown error
Mar 13 09:27:08 ipa.example.com gssproxy[3887]: (OID: { 1 2 840 113554 1 2 2 }) The referenced credential has expired, Unknown error
Mar 13 09:27:08 ipa.example.com gssproxy[3886]:     GSSX_RES_ACQUIRE_CRED( status: { 720896 { 1 2 840 113554 1 2 2 } 0 "The referenced credential has expired" "" [  ] } output_cred_handle: <Null> )
</pre>

**Comment by abbra** [comment]
A restart of httpd fixes the problem.

**Comment by simo5** [comment]
Turns out this is a bug in gssproxy

**Comment by abbra** [comment]
@simo5 found it is a bug in gssproxy: https://pagure.io/gssproxy/pull-request/171
