### ISSUE TITLE
GssapiExpectedNameAttribute option

### ISSUE THREAD

**Issue by mrogers950** [modauthgssapi/mod_auth_gssapi#137]
This option would be for restricting authorization to clients that hold one or more specific name attributes. On a failure we should return HTTP_FORBIDDEN (403), and fill the environment with an indication that a required name attribute was missing. 
There should be a way to specify an AND/OR combination of string-type name attributes, using some familiar syntax. E.g.,
GssapiExpectedNameAttribute &(auth-indicator=pkinit,auth-indicator=otp)
(WIP branch is at https://github.com/mrogers950/mod_auth_gssapi/commit/54999a4e321577649302329f69d6889126f50e2c )

**Comment by simo5** [comment]
Just for the record:
we had a f2f call where we discussed handling full composablity of and/or/not rules.
I suggested a filter like LDAP is a possible solution albeit the syntax is not super friendly, a non-prefix notation for handling composable filters might be more friendly: (x=1 and (y=2 or z=*))
In the case of a full filtering syntax we'd need a parser and a matcher that can return a sensible error when a branch condition fails, for exanmple it will be hard to report what went wrong in the filter above if x is indeed 1 but there is no y or z attributes present, or both are present but neither match ...

**Comment by mrogers950** [comment]
Should the error say anything about the expected value on a failure? I was thinking just a generic "missing attribute" error. Less info disclosed and also would cut down the complexity of the matcher.

**Comment by simo5** [comment]
I do not know what we can say, the attribute may be present but with the incorrect value, or maybe multiple attributes are required and only one is mismatched. I am tempted to return the expression filled with what we have but I am not sure how useful that would be to an application, so perhaps in the first revision we can simply return a: "filter mismatch error" and see if people think that's enough.

**Comment by simo5** [comment]
implemented in #140
