### ISSUE TITLE
Channel Binding Tokens Support

### ISSUE THREAD

**Issue by jborean93** [modauthgssapi/mod_auth_gssapi#141]
Hi

I've been trying to find a way to test out some channel binding code I'm writing  and I've been finding some vague mentions to this supporting it but can't find any concrete evidence. I can see you have a test branch from a few years ago here https://github.com/simo5/mod_auth_gssapi/tree/rfc5929 but I'm not sure on what the status is on it and whether it works.

Do you have an update on the latest support for channel bindings or if that test branch might be what I'm looking for?

Thanks

Jordan

**Comment by simo5** [comment]
Hi @jborean93,
I have not worked on that branch for a while, although I am planning to, again once we can land patches that make MIT's GSSAPI able to conditionally do channel bindings. ATM in MIT if you specify channel bindings on the server side than any client that doesn't do CB (IE *all*) will just fail.

On the actual CB work, this was the status when I last touched that branch:
- The code relies on patches to mod_ssl that went upstream some time ago, but I am not sure they ever landed in Apache 2.4, I think they are available only in the development branch for now.
- The code was tested only against a Windows IIS server with the NTLMSSP mechanism.
- The code did work properly.

So I would say that from the POV of mod_auth_gssapi, with the limited testing I made things should be more or less complete. However the dependcies are not there yet.

HTH,
Simo.

**Comment by jborean93** [comment]
Thanks for the info @simo5, I thought that may have been the case and was looking for some easy wins to build a web site on a non Windows platform to test the Channel Bindings code I've written.

Thanks

Jordan
