### ISSUE TITLE
No REMOTE_USER in request headers

### ISSUE THREAD

**Issue by tkdchen** [modauthgssapi/mod_auth_gssapi#143]
I use this configuration and Basic auth works well, but there is no ``REMOTE_USER`` in request headers passed to my application behind Apache. My app is running with mod_wsgi.
```
AuthType GSSAPI
AuthName "GSSAPI Single Sign On Login"
#GssapiBasicAuth On
GssapiCredStore keytab:/etc/httpd/httpd.keytab
Require valid-user
```

When I add

```
RequestHeader set X-Remote-User %{REMOTE_USER}s
```

``X-Remote-User`` presents in request headers with correct value. However, following config doesn't work.

```
RequestHeader set REMOTE_USER %{REMOTE_USER}s
```

Is there anything I missed to configure mod_auth_gssapi so that it can set REMOTE_USER automatically in the headers?

I'm using ``mod_auth_gssapi-1.5.0-1.fc25.x86_64``.

**Comment by frozencemetery** [comment]
I believe in order to set `REMOTE_USER` you need to do something like `GssapiLocalName on`.

**Comment by tkdchen** [comment]
Any other settings should be turned on along with ``GssapiLocalName``? I turned it on, still no ``REMOTE_USER`` in request headers and environment variables. My app running behind Apache is a flask app, I'm not sure if this is relative.

**Comment by simo5** [comment]
@tkdchen there are 2 kind of variables in apache, REMOTE_USER is not a request header, but it is an apache environemnt variable. You will not find it in the request Headers.
