### ISSUE TITLE
Mechanism needs continuation but neither GssapiConnectionBound nor GssapiUseSessions are available

### ISSUE THREAD

**Issue by mortenn** [modauthgssapi/mod_auth_gssapi#144]
I have added `GssapiConnectionBound On` to my config, but I still get the warning

`Mechanism needs continuation but neither GssapiConnectionBound nor GssapiUseSessions are available`

This happens when a user not authorized by mod_authnz_ldap tries connecting. As an authorized user, there are no errors being logged.

**Comment by simo5** [comment]
you shouldn't add GssapiConnectionBound unless you know exactly what you are doing :)
Are you using sessions ?

**Comment by mortenn** [comment]
I tried setting up sessions, but the cookies didn't want to work, so I abandoned that.
I only added "GssapiConnectionBound" because that error was telling me to, kind of.

**Comment by frenche** [comment]
Kerberos mechanism should complete on the first call and should not require continuation, try to troubleshoot as a Kerberos issue, perhaps with wireshark.

**Comment by mortenn** [comment]
The kerberos authentication completes, but then authnz_ldap fails due to the user not being in the required ldap-group, that is when this warning happens.

**Comment by simo5** [comment]
Perhaps authz_ldap returns an error immediately and does not let mod_auth_gssapi return the proper updated cookie back. Sounds more like a configuration issue/authx_ldap module issue than a problem with mod_auth_gssapi

**Comment by mortenn** [comment]
I have no idea, I just set up authnz_ldap and auth_gssapi and got this warning.
Not using session or cookies here.

Authentication completes, as authnz_ldap gets the user and can look up group memberships fine.

**Comment by bluikko** [comment]
mod_auth_kerb was working without any issues for me. I changed to mod_auth_gssapi + gssproxy for the obvious reasons, and I am seeing this warning also.

After setting "GssapiConnectionBound On" it works sometimes:
- main page (https://site.host.domain/) works 100% of the time;
- sub-pages in a rather complex PHP application work between sometimes and almost never.

Could you expand on "you shouldn't add GssapiConnectionBound unless you know exactly what you are doing"?

**Comment by bluikko** [comment]
So I bite the bullet and compiled 1.5.1 from source.
Everything works 100%.

I am convinced the EL7 mod_auth_gssapi 1.4.0 has problem with the subrequest handling.

**mod_auth_gssapi should be updated to 1.5.1 on EL7!!!**

**Comment by frozencemetery** [comment]
@bluikko, el7.4 (i.e., latest el7) does have 1.5.1.  However, I don't think there's a CentOS release of that yet.

**Comment by mortenn** [comment]
In my case it's just a warning when an unauthorized user connects, it works properly for authorized users.

**Comment by simo5** [comment]
If you do not know what GssapiConnectionBound does it means you should definitely not use it.
I know it sounds like "trust me" but it kinda is :-)

**Comment by frozencemetery** [comment]
(If you find that unsatisfying: GssapiConnectionBound effectively controls mod_auth_gssapi's authentication state storage when using "chatty" mechanisms.  To be clear, normal krb5 usage will not require this setting, but, for instance, NTLM will.  [Don't use NTLM if you can avoid it.](https://en.wikipedia.org/wiki/NTLM#Weakness_and_Vulnerabilities))

**Comment by simo5** [comment]
seem resolved, closing

**Comment by mortenn** [comment]
As this issue was originally posted, I'd say yes.
But I also think that the warning in question being logged when the authentication part of the request has completed successfully, but the authorization check fails seems misleading.
