### ISSUE TITLE
Two modernization nitpicks

### ISSUE THREAD

**Issue by mcepl** [modauthgssapi/mod_auth_gssapi#163]
https://github.com/modauthgssapi/mod_auth_gssapi/blob/1a3598e359abf5356533c8802397c3dc357fdc9c/tests/magtests.py#L10

What is the lowest supported version of Python required? If it is at least ``2.6``, then you can throw away ``strings.Template`` templates and use ``str.format()`` (just don’t forget to double ``{`` and ``}`` where you want them; otherwise it is just matter of ``%s/\${/{/gc`` command). Whole ``strings`` module has been deprecated for years.

Also, if it is at least ``2.7`` then you can replace all those complicated constructs with ``subprocess.Popen()`` with ``if subprocess.call(...) != 0:``. A way less readable IMHO and you save some unnecessary variables.

**Comment by frozencemetery** [comment]
I believe we do need to support 2.6 since that's what's in el6.
