### ISSUE TITLE
The connection was reset while using Basic Auth

### ISSUE THREAD

**Issue by hlavki** [modauthgssapi/mod_auth_gssapi#165]
When authentication falls to basic auth, enter credentials and then it fails on "The connection was reset" error. What is strange, it only happens in firefox, chrome is OK.
The workaround is to set the apache configuration parameter KeepAliveTimeout to higher value, but I do not think this is a good option. Apache sends the default keep-alive header of `Keep-Alive: timeout = 5, max = 100`.

**Comment by frozencemetery** [comment]
A similar issue was found to be an issue in firefox.  Can you try again with the latest version of firefox and see if it's fixed?

**Comment by frozencemetery** [comment]
Have not heard back in several months, so closing since we do not have enough information.  If you are experiencing this issue still and can provide this information, please reopen and we'll debug further!

**Comment by jb-wisemo** [comment]
As of today, this is still happening with the latest Pale Moon browser (a backwards compatible but fully maintained Firefox fork).  Browser version is 28.7.2 (Windows 32 bit).

This happens in a setup where there are also unexplained authentication failures from other browsers with useless debug logging (a separate but related issue).

**Comment by frozencemetery** [comment]
Given it isn't an issue with firefox (as far as I know...), I recommend you take that up with them.  Feel free to link the report here and I'll follow along, though.
