### ISSUE TITLE
kerberos support documentation

### ISSUE THREAD

**Issue by yakoub** [modauthgssapi/mod_auth_gssapi#166]
can you direct me to some reference documentation to configure apache for kerberos single sign-on support ?
i have abstract knowledge of the processs but not enough in depth to figure it all out on my own .

our organization already have kerberos service running, i just need to configure apache to communicate with it .

**Comment by simo5** [comment]
There are some directions here: https://www.freeipa.org/page/Web_App_Authentication/Example_setup#Kerberos
They are a bit freeipa specific, but you should be able to adapt it to other kerberos based systems if you have a bit of knowledge about kerberos based systems.

**Comment by frozencemetery** [comment]
For httpd.conf, there's an example config in our README section [here](https://github.com/modauthgssapi/mod_auth_gssapi#configuration).  There's also a variety of different configurations in our test suite's [httpd.conf](https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/tests/httpd.conf#L155).
