### ISSUE TITLE
software requirements 

### ISSUE THREAD

**Issue by yakoub** [modauthgssapi/mod_auth_gssapi#169]
it is written that "MIT krb5 (>=1.11)" is required .
which part of that software exactly is required ?

i don't need to run kdc server, since mod_auth_gssapi is supposed to connect to 
different server running kdc and our organization already has that .
so does that mean i only need the client program of kerberos ?

**Comment by spaetow** [comment]
The GSSAPI client libraries, yes.

**Comment by simo5** [comment]
If you just want to run mod_auth_gssapi then you need the krb5 and gssapi libraries only.
If you want to run the test suite at build time you need all components including the KDC.
