### ISSUE TITLE
REMOTE_USER

### ISSUE THREAD

**Issue by yakoub** [modauthgssapi/mod_auth_gssapi#170]
as i understood after this modules finished its work, it assigns value to the REMOTE_USER environment value .

but i couldn't find further documentation .

what is this value that is assigned to REMOTE_USER when choosing GssapiBasicAuthMech krb5 ?
does it depend on the mechanism that was configured ?

**Comment by yakoub** [comment]
does the environment variable REMOTE_USER persist through whole user session or only after initial kerberos "handshake" ?
i mean as long as the user stays in the location defined in apache as having GssapiBasicAuthMech krb5 .

**Comment by simo5** [comment]
If GssapiLocalname is on REMOTE_USER is set to the value returned by gss_localname() which usually is set to the stringified principal name without the @REALM part. It may be set to other stuff if the krb5.conf on your system defines different strategies for mapping.
If GssapiLocalname is off then REMOTE_USER is set to the full stringified principal name.

Note that the variable REMOTE_USER is set by apache itself based on the user identity reported back by the authentication module.
mod_aut_gssapi always sets GSS_NAME to the full stringified principal name.

Both variables are always set on each authenticated request, regardless of the authentication type.
Data is saved in the session cookie so it happens also for cases when auth happens only once and the following request rely on the session cookie for authentication.
