### ISSUE TITLE
syntax error near unexpected token `OPENSSL,'

### ISSUE THREAD

**Issue by thuiban** [modauthgssapi/mod_auth_gssapi#172]
Hey guys, i have problem to install mod_auth_gssapi, when i try this command `./configure`, it makes an error : 
`./configure: line 13161: syntax error near unexpected token `OPENSSL,'
./configure: line 13161: `PKG_CHECK_MODULES(OPENSSL, openssl)'`

I installed pkg-config and other think like libssl ... 

I use ubuntu container docker.

Can you help me ?

**Comment by frozencemetery** [comment]
Did you run `autoreconf -fi` first?

**Comment by thuiban** [comment]
Yes i did that in first

**Comment by simo5** [comment]
@thuiban what version of mod_auth_gssapi ?
Do you have the openssl devel libs installed on the system ?

**Comment by saxonww** [comment]
I just ran into this as well. The problem is that on Ubuntu (16.04 at least) you don't get PKG_CHECK_MODULES with build-essential, autoconf, automake, or autotools-dev - it's in pkg-config.

**Comment by simo5** [comment]
@saxonww are you saying we miss a dependency on Ubuntu ? Or something else ?
Seem like what you are saying is that configure should check for pkg-config ?
(yes we definitely should check for felx/bison being present).

A patch would be nice :-)

**Comment by saxonww** [comment]
Well the weird thing is that I think configure is already checking for bison and flex, because I saw that scroll by in the output - it just evidently didn't fail on them being missing.

I will see if I can make a patch. I don't have any direct experience with automake/autotools, so no promises.
