### ISSUE TITLE
Can't get GssapiLocalName to work

### ISSUE THREAD

**Issue by saxonww** [modauthgssapi/mod_auth_gssapi#176]
I'm using mod_auth_gssapi 1.3.2 with MIT Kerberos 1.13.2 and Apache 2.4.18 - all default versions from packages - on Ubuntu 16.04. I have also tested with a version compiled from 0b746d2. My Kerberos environment is Active Directory. I have included relevant configuration below.

/etc/apache2/sites-enabled/site.conf:
```ApacheConf

        LogLevel debug

        <Location /php>
                AuthType GSSAPI
                AuthName "GSSAPI SSO Login"
                GssapiCredStore keytab:/etc/httpd.keytab
                GssapiBasicAuth On
                GssapiBasicAuthMech krb5
                GssapiAllowedMech krb5
                GssapiLocalName On
                Require valid-user
        </Location>
```

What I think this is supposed to do is:

- Set the auth type to GSSAPI with the specified keytab (which exists and is readable)
- Enable Basic Authentication
- Restrict the allowed mechanisms to krb5
- Convert REMOTE_USER from the default user principal name to whatever krb5.conf says it should be based on the auth_to_local options for the realm of the authenticating user

/etc/krb5.conf:
```INI
[realms]

    NON.DEFAULT.REALM.COM = {
        kdc = mykdc.non.default.realm.com
        admin_server = mykdc.non.default.realm.com
        auth_to_local = RULE:[1:$1@$0](.*@NON\.DEFAULT\.REALM\.COM)s/@.*//
    }

```

I think this should map principals for _user_@NON.DEFAULT.REALM.COM to just _user_.

I've got a single file /php/phpinfo.php which just calls phpinfo() for debugging. What I'm seeing when I access it is that I get prompted for authentication even if I have a valid ticket, and the debug output contains this:

```
[auth_gssapi:error] [pid 19888] [client 192.168.0.123:63528] gss_localname() failed: [The operation or option is not available or unsupported (No such file or directory)]
```

If I remove GssapiLocalName from my config, I can authenticate via ticket and basic auth. I have the relevant gssapi_ext stuff installed, and I actually rebuilt mod_auth_gssapi against master and tried with that but get the same error; during configure I saw that gssapi_ext.h was available/supported so I think gss_localname() should be working. I think this is probably just a configuration issue on my end, but I am not sure what that error message is really telling me or what to look at next.

**Comment by saxonww** [comment]
I remove that from krb5.conf, login works for the default realm even if GssapiLocalName is on. But it continues to fail with the same gss_localname() error for other realms. If I remove GssapiLocalName from my configuration I can complete an authentication from any realm, but then the REMOTE_USER is the full principal name.

I may by trying to solve a different problem with this GssapiLocalName setting. What's really happening is that I am trying to offload AD authentication for a backend web service (Jenkins) to Apache; Jenkins takes the authenticated username in a header (allegedly) and uses that to look up user details via LDAP. I've done this successfully with mod_auth_kerb for years, but I want to move to mod_auth_gssapi.

The actual configuration I am trying is this:

```ApacheConf
    ProxyRequests Off
    ProxyPreserveHost On
    AllowEncodedSlashes NoDecode

    ProxyPass / http://localhost:8080/ nocanon
    ProxyPassReverse / http://localhost:8080/

    <Proxy http://localhost:8080/*>
            Order deny,allow
            Allow from all
    </Proxy>

    <LocationMatch "^/(?!assets|avatar-cache|cli|git|instance-identity|jnlpJars|whoAmI)">
            AuthType GSSAPI
            AuthName "GSSAPI SSO Login"
            GssapiCredStore keytab:/etc/httpd.keytab
            GssapiBasicAuth On
            GssapiBasicAuthMech krb5
            GssapiAllowedMech krb5

            Require valid-user

            RequestHeader unset X-Forwarded-User
 
            RewriteEngine On
            RewriteCond %{LA-U:REMOTE_USER} (.+)@.*
            RewriteRule .* - [E=RU:%1]

            RequestHeader set X-Forwarded-User %{RU}e
    </LocationMatch>
```

The actual behavior I'm seeing is that without GssapiLocalName, ticket authentication works for all realms. Basic authentication does not seem to work; I get past the GSSAPI basic prompt, but then Jenkins prompts for user/pass and will not take anything that I give it, eventually complaining that it can't look up `user@REALM`. So I was thinking that if I could just strip the `@REALM` part with GssapiLocalName then I would just sidestep that issue.

Jenkins is actually supposed to be looking at an X-Forwarded-User header, which I am setting by rewriting REMOTE_USER and writing the result to that header. I haven't exhausted every testing option that I have, but everything I have tried so far makes me think that X-Forwarded-User is being set correctly, or in some cases it's just not being set at all - which would cause Jenkins to prompt me. I am not sure why Basic authentication would behave differently than ticket authentication in this scenario, but it appears to be.

FWIW if I just replace REMOTE_USER with GSS_NAME in my RewriteCond, X-Forwarded-User is always null. I haven't spent more than 5 seconds trying that so it's likely I would need to make other changes.

**Comment by simo5** [comment]
Sounds like this was a user configuration issue.
Please reopen if you think there is an actual bug in mod_auth_gssapi
