### ISSUE TITLE
Issue with mismatched UPN/sAMAccountName

### ISSUE THREAD

**Issue by mortenn** [modauthgssapi/mod_auth_gssapi#181]
Hi,

Due to an ongoing migration to office 365, our UPNs and sAMAccountNames no longer match.
This has caused a small issue with one service, where we use gssapi in combination with ldap to do aaa;

```
AuthLDAPUrl "ldaps://.../?userPrincipalName"
AuthLDAPBindDN "..."
AuthLDAPBindPassword "..."

AuthType GSSAPI
GssapiBasicAuth Off
GssapiSSLonly On
GssapiUseSessions Off
GssapiConnectionBound On
GssapiAllowedMech krb5
GssapiCredStore keytab:...

require ldap-group CN=...
```

Before I changed my UPN, this was working fine.
I can see the sAMAccountName in the access logs, with @domain.com
Previously, this would match the upn.

I've tried changing the LDAPUrl to ?sAMAccountName, but that didn't work.
Presumably because the ldap auth gets passed MNI@DOMAIN.COM which will neither match the sAMAccountName nor the UPN.

Any suggestions on how to fix this?

**Comment by simo5** [comment]
Do you have any attribute in LDAP matching the new name ?
You can also use krb5 principal mapping to get a GSSLocalname that will match samaccountname without the domain part, see the auth_to_local directive in krb5.conf(5)
You will get that name using the option GssapiLocalName On

Off topic: please fix your config by GssapiUseSessions -> On and GssapiConnectionBound -> Off, it won't solve this problem, but it is highly unlikely you want your current config.

**Comment by frenche** [comment]
> I've tried changing the LDAPUrl to ?sAMAccountName, but that didn't work.
Presumably because the ldap auth gets passed MNI@DOMAIN.COM which will neither match the sAMAccountName nor the UPN.

Can't the username string be cut at the at-sign using regex somehow?

**Comment by simo5** [comment]
@frenche yes by using auth_to_local and GSSLocalname

**Comment by mortenn** [comment]
When I set this up initially, I couldn't get sessions to work at all.

**Comment by mortenn** [comment]
I set up auth_to_local in krb5.conf, but then I just get a GSS error:
```[client 10.9.80.5:64220] GSS ERROR gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information ( SPNEGO cannot find mechanisms to negotiate)]```

I tried various methods in krb5.conf;
```
 DOMAIN.COM = {
        kdc = domain.com
        admin_server = domain.com
        auth_to_local = {
                RULE:[1:$1@$0]s/(.*)@.*/DOMAIN\$1/
        }
 }
```
No matter what I put for the rule, I got the same gss error.
Rules I tried (one at a time);
```
RULE:[1:$1@$0]s/(.*)@.*/DOMAIN\$1/
RULE:[1:$1@$0]s/(.*)@.*/DOMAIN\\$1/
RULE:[1:$1@$0]s/@.*//
RULE:[1:$1](@HAPRO.NO)s/@.*//
```

If I just comment out the RULE line in krb5.conf, authentication works fine, but I can't authorize.
Removing ldap lookup and using require valid-user does work, but I would like to limit access to those authorized by a group in AD.

Changing the UseSessions/ConnectionBound options doesn't seem to affect anything, so I've done so.

  // Regards, Morten

**Comment by mortenn** [comment]
It turns out that setting `GSSLocalname On` without any changes to krb5.conf and changing the `AuthLDAPUrl` to `...?sAMAccountName` fixed my issue.

**Comment by mortenn** [comment]
Still having this issue with another system where I've got sssd set up, as that makes the local name samaccountname@example.com But as the data being exposed on that server is less sensitive, I'm not terribly fussed if all internal users can access it.
