### ISSUE TITLE
GssapiImpersonate without ok_to_auth_as_delegate

### ISSUE THREAD

**Issue by cantonese84** [modauthgssapi/mod_auth_gssapi#182]
Here is the Apache configuration for the Location:

<Location "/login.php">
    SSLRequireSSL

    GssapiImpersonate On
    GssapiCredStore keytab:/etc/httpd/httpd.keytab
    GssapiCredStore client_keytab:/etc/httpd/httpd.keytab
    
    GssapiUseSessions On
    Session On
    SessionCookieName sessionIPA path=/;httponly;secure;

    InterceptFormPAMService nagios
    InterceptFormLogin username
    InterceptFormPassword password
    InterceptFormPasswordRedact on
</Location>

The above works: intercept_form_submit intercepted the POST, PAM authentication passed, and session cookie was created.  However, the service principal in /etc/httpd/httpd.keytab was not set for ok_to_auth_as_delegate.  Did I miss something?  I thought ok_to_auth_as_delegate was required for s4u2self to work.  Is this expected?  The KDC and Apache server are all running Centos 7.5, and ipa server and client version is 4.5.4-10.

**Comment by simo5** [comment]
s4u2self always works, it's s4u2proxy that requires authorization
