### ISSUE TITLE
Error during make instruction

### ISSUE THREAD

**Issue by raphaelgon** [modauthgssapi/mod_auth_gssapi#184]
Hi,

I am getting an error during installation.

After 'make' command, I got this warming:

mv -f .deps/mod_auth_gssapi_la-sessions.Tpo .deps/mod_auth_gssapi_la-sessions.Plo
/usr/lib64/apr-1/build/libtool --silent  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -I ./asn1c  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX -D_REENTRANT -D_GNU_SOURCE   -pthread    -I/usr/include/httpd  -I/usr/include/apr-1  -fPIC -g -O2 -MT mod_auth_gssapi_la-environ.lo -MD -MP -MF .deps/mod_auth_gssapi_la-environ.Tpo -c -o mod_auth_gssapi_la-environ.lo `test -f 'environ.c' || echo './'`environ.c
environ.c: In function 'mag_set_required_name_attr':
environ.c:111:5: warning: implicit declaration of function 'ap_log_rdata' [-Wimplicit-function-declaration]
     ap_log_rdata(APLOG_MARK, APLOG_DEBUG, req, mc->required_name_attrs[count],

And then after 'make install' , when I try to reload Apache, I got this error msg:
Cannot load modules/mod_auth_gssapi.so into server: /etc/httpd/modules/mod_auth_gssapi.so: undefined symbol: ap_log_rdata

My system:

[root@6207fdff9d77 mod_auth_gssapi-1.6.1]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

[root@6207fdff9d77 mod_auth_gssapi-1.6.1]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59

Thanks

**Comment by simo5** [comment]
Seems like ap_log_rdata was added in Apache 2.4.11, so it is not available in the CentOS build of Apache. We'll have to add a build check I guess...

**Comment by raphaelgon** [comment]
Thank you!
