### ISSUE TITLE
Fix compilation with OpenSSL < 1.1.0 and >= 0.9.8b

### ISSUE THREAD

**Issue by rainerjung** [modauthgssapi/mod_auth_gssapi#188]
File src/crypto.c contains a definition of EVP_CIPHER_CTX_new() and EVP_CIPHER_CTX_free() if the module gets compiled against OpenSSL older than 1.1.0. But those two symbols have been introduced in OpenSSL 0.9.8b. For any version starting with 0.9.8b and older than 1.1.0 the compilation fails, because there are two definitions of the same symbols:

```
/path/to/openssl/lib/libcrypto.a(evp_enc.o): In function `EVP_CIPHER_CTX_new':
/path/to/openssl-src/crypto/evp/evp_enc.c:87: multiple definition of `EVP_CIPHER_CTX_new'
.libs/mod_auth_gssapi_la-crypto.o:/path/to/mod_auth_gssapi-1.6.1/src/crypto.c:31: first defined here
/path/to/openssl/lib/libcrypto.a(evp_enc.o): In function `EVP_CIPHER_CTX_free':
/path/to/openssl-src/crypto/evp/evp_enc.c:551: multiple definition of `EVP_CIPHER_CTX_free'
.libs/mod_auth_gssapi_la-crypto.o:/path/to/mod_auth_gssapi-1.6.1/src/crypto.c:44: first defined here
collect2: error: ld returned 1 exit status
```

The following patch fixes this:

```
--- src/crypto.c 2017-08-07 16:36:55.735998000 +0200
+++ src/crypto.c 2018-09-12 15:05:05.584623000 +0200
@@ -26,7 +26,9 @@
     HMAC_CTX_cleanup(ctx);
     OPENSSL_free(ctx);
 }
+#endif

+#if OPENSSL_VERSION_NUMBER < 0x0090802fL || defined(LIBRESSL_VERSION_NUMBER)
 EVP_CIPHER_CTX *EVP_CIPHER_CTX_new(void)
 {
     EVP_CIPHER_CTX *ctx;
```

**Comment by rainerjung** [comment]
For reference:

1) NEWS from OpenSSL 0.9.8b

>   Major changes between OpenSSL 0.9.8a and OpenSSL 0.9.8b:
> ...
>       o New functions EVP_CIPHER_CTX_new() and EVP_CIPHER_CTX_free().

2) CHANGES from OpenSSL 0.9.8b

>  Changes between 0.9.8a and 0.9.8b  [04 May 2006]
> ...
>   *) New functions EVP_CIPHER_CTX_new() and EVP_CIPHER_CTX_free() to support
>      opaque EVP_CIPHER_CTX handling.
>      [Steve Henson]

3) Header file evp.h

> ...
> EVP_CIPHER_CTX *EVP_CIPHER_CTX_new(void);
> void EVP_CIPHER_CTX_free(EVP_CIPHER_CTX *a);
> ...

The symbols are defined in all later versions. They are not defined in 0.9.8a.

Finally the version string for 0.9.8b is:

> #define OPENSSL_VERSION_NUMBER  0x0090802fL

**Comment by simo5** [comment]
You mean newer than 1.1.0, not older, right ?

**Comment by simo5** [comment]
Ah Iread it backwards,
point is compilation fails between versions 0.9.8a < X < 1.1.0

Please open a PR with the patch above.

**Comment by simo5** [comment]
Actually, I think the better path would be to have a configure check to see if the functions exist, and define them only if they don't, using version numbers is bogus as distro backports could invalidate the check ...

**Comment by rainerjung** [comment]
Note that you are already using a version check in that file, but the version checked is wrong for these two symbols. Of course a configure check would be better, but it is often more complex to get it right (eg. not using system openssl include files and libraries) so I preferred to improve the existing check.

If possible I would like to spare the time and not open a pull request for that tivial change.

**Comment by simo5** [comment]
Please check if pull #189 works for your case

**Comment by simo5** [comment]
@rainerjung any chance you can test the above PR and see if it works right for you ?

**Comment by rainerjung** [comment]
I tested the patch with the regenerated "configure" against OpenSSL 1.0.2p. This works now (and had not worked before without patching). Thanks!
