### ISSUE TITLE
move from mod_auth_kerb to mod_auth_gssapi

### ISSUE THREAD

**Issue by bekkibobbek** [modauthgssapi/mod_auth_gssapi#190]
I try to use mod_auth_gssapi for sso with nextcloud 13 on Apache/2.4.18 (Ubuntu) and Kerberos 5 version 1.13.2
Before I used mod_auth_kerb which worked.
Aren't the following config snippet equivalent? What would I have to change in order to use mod_auth_gssapi?
It seems weird that there are no log entries from mod_auth_gssapi - is it even called? kdc logs dont reveal anything with mod_auth_gssapi (but with mod_auth_kerb)

With mod_auth_gssapi enabled, nextcloud says there is no corresponding username or apache says:
```
Unauthorized

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
```
I don't know under which circumstances I got the nextcloud error messages - maybe after toggling the mods (and not closing the browser, so that the kerb ticket was still valid?)

mod_auth_kerb
config:
```
<Location "/index.php/login">
    AuthType Kerberos
    KrbServiceName cloud
    KrbAuthRealms REALM
    Krb5KeyTab /etc/keytab
    Require valid-user
</Location>
```
log:
```
   mod_authz_core.c(809): -:  AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer -
   src/mod_auth_kerb.c(1971): -:  kerb_authenticate_user entered with user (NULL) and auth_type Kerberos, referer -
   src/mod_auth_kerb.c(1049): -:  Using svc/svc.fqdn@ as server principal for password verification, referer -
   src/mod_auth_kerb.c(753): -:  Trying to get TGT for user user@REALM, referer -
   src/mod_auth_kerb.c(663): -:  Trying to verify authenticity of KDC using principal svc/svc.fqdn@, referer -
   src/mod_auth_kerb.c(1131): -:  kerb_authenticate_user_krb5pwd ret=0 user=user@REALM authtype=Basic, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require valid-user : granted, referer -
```
mod_auth_gssapi
config:
```
<Location "/index.php/login">
  AuthType GSSAPI
  GssapiCredStore keytab:/etc/keytab
  GssapiAllowedMech krb5
  Require valid-user
</Location>
```
log:
```
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer -
   mod_headers.c(899): -:  AH01503: headers: ap_headers_error_filter(), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require all granted: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: granted, referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer -
   mod_headers.c(899): -:  AH01503: headers: ap_headers_error_filter(), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer -
   mod_authz_core.c(809): -:  AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer -
   mod_headers.c(899): -:  AH01503: headers: ap_headers_error_filter(), referer -
```

**Comment by simo5** [comment]
I think MIT 1.13.2 is too old for the GssapiCredStore option.
You'll have to set the KRB5_KTNAME env var in the Apache startup scripts if you want to keep using that version. I would recommend upgrading MIT krb5 to 1.16 though.

**Comment by bekkibobbek** [comment]
I just tried with 
```
export KRB5_KTNAME=/etc/keytab
```
in /etc/apache2/envvars but that did not change anything.

I also tried KRB5_TRACE=/tmp/log there and the files was created but empty after I visited the page.
I would expect that there would be some kerberos log output put there?

**Comment by simo5** [comment]
Are you sure you are loading the gssapi module in apache?
There should be at least some lines in the apache log

**Comment by bekkibobbek** [comment]
Yes, it seems that the module is enabled:
```
apache2ctl -t -D DUMP_MODULES|grep auth_gssapi_module
 auth_gssapi_module (shared)
```
Could there be an inteference with other modules or something?

**Comment by simo5** [comment]
Check if the module returned any error early on at apache startup

**Comment by bekkibobbek** [comment]
Using loglevel trace8 the only log entry related to gssapi is:
```
[mpm_prefork:notice] [pid 26287:tid -] prefork.c(1022): -: [client -] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_gssapi/1.3.3 mod_auth_kerb/5.4 OpenSSL/1.0.2g configured -- resuming normal operations, referer -
```

**Comment by frozencemetery** [comment]
Did you leave mod_auth_kerb configured?  Can you remove that?

**Comment by bekkibobbek** [comment]
Sorry, I am retarded. Firefox wasn't set to negotiate
(about:config -> network.negotiate-auth.trusted-uris: example.com)
Now the mod yields 
```gss_accept_sec_context() failed: [An unsupported mechanism was requested (Unknown error)] ```
That is probably due to the fact that Firefox is running on a windows which tries NTLM 

My apache conf looks now like that:
```
<VirtualHost *:123>
BrowserMatch Windows gssapi-no-negotiate
<Location "/index.php/login">
  AuthType GSSAPI
  GssapiCredStore keytab:/etc/keytab
  GssapiAllowedMech krb5
  Require valid-user
</Location>
</VirtualHost>
```

My goal is to use the username provided to a prior vpn connection as username - not the windows username. Is there any way I can make that work? The vpn connection is already authenticated via kerberos - so the tgt should be available?!

**Comment by frozencemetery** [comment]
I don't know enough about Windows to answer that.  Simo, do you?

**Comment by simo5** [comment]
I do not know, it probably depend son what krb5 libs firefox is using, if SSPI it will default to the windows credentials.
But this is not a mod_auth_gssapi issue anymore.

**Comment by bekkibobbek** [comment]
Ok, then back to topic :D 
(you were right with the krb5 lib ; about:config -> network.negotiate-auth.gsslib;C:\Program Files\MIT\Kerberos\bin\gssapi64.dll - for those who will run into the same problem)
Now the kdc log shows entries like:
```
LOOKING_UP_SERVER: authtime 0,  user@REALM for HTTP/fqdn@REALM, Server not found in Kerberos database
```
That is due to the fact that the service name is not HTTP but cloud.
With mod_auth_kerb I could define KrbServiceName.
How would I achieve the same with mod_auth_gssapi? Or is this related to the lib too?

Thanks for your input - that was really helpful :)

**Comment by simo5** [comment]
You cannot specify the service name as the standard requires you to use HTTP so we did not make the service name configurable.

**Comment by simo5** [comment]
Note that browsers and most http libraries can and will only try with HTTP/ so setting a different service name is generally not useful.
