### ISSUE TITLE
Basic Auth and OTP

### ISSUE THREAD

**Issue by masevcik** [modauthgssapi/mod_auth_gssapi#200]
Hi, I have svn server with mod_auth_gssapi authentication, backend is FreeIPA server. Basic Auth works fine for username/password but I cannot authenticate using OTP, I just get gss error:

`[client 172.17.80.3:55112] GSS ERROR In Basic Auth: gss_acquire_cred_with_password() failed: [Unspecified GSS failure.  Minor code may provide more information (Pre-authentication failed: Invalid argument)]`

I guess the problem might be that the Basic Auth is not using FAST channel, but I have no idea how to configure it. 

Apache config:

```
<Location /svn>
        DAV svn
        SVNParentPath /var/lib/svn
        AuthType GSSAPI
        AuthName "Kerberos Login"
        GssapiBasicAuth On
        GssapiCredStore keytab:/etc/httpd/http.keytab
        GssapiCredStore ccache:MEMORY:user_ccache
        Require valid-user
</Location>
```
Is it possible to use Basic Auth with OTP?

Thanks
Martin.

**Comment by simo5** [comment]
Ys, OTP requires fast, and GSSAPI does not support using OTP in password authentication so mod_auth_gssapi doesn't either. Sorry.
