### ISSUE TITLE
How to allow SSO through a reverse proxy?

### ISSUE THREAD

**Issue by alexpdp7** [modauthgssapi/mod_auth_gssapi#201]
Hi,

I have mod_auth_gssapi working on https://foo.internal.my.domain/ , doing SSO with Firefox against a FreeIPA server.

However, I have https://foo.my.domain/ acting as a reverse proxy to that, with no mod_auth_gssapi to provide external access to this system. Basic authentication works fine through the reverse proxy, but SSO doesn't tick.

Is there any way to enable this to happen? I'd really prefer the reverse proxy to be dumb and not to gssapi itself, and have authentication handled in a single place... while having the internal server be as secure as possible.

Cheers,

Álex

**Comment by simo5** [comment]
You probably just need a keytab for HTTP/foo.my.domain on the internal server, you can add an alias in FreeIPA on the foo.internal.my.domain object or create anew host object and add the keys in the HTTP server's keytab.
This is not a mod_auth_gssapi issue though, so closing.
I suggest writing to frreipa-users mailing lists for further help on this matter.

**Comment by alexpdp7** [comment]
If someone happens to stumble across this in Google, yeah, that's accurate.

I created a host entry in FreeIPA for the external host name, then created a service for it.

Used `ipa-getkeytab` to retrieve the keytab for the new service, adding it to the existing keytab and voila it works.
