### ISSUE TITLE
Sweeper doesn't work with gssproxy

### ISSUE THREAD

**Issue by frozencemetery** [modauthgssapi/mod_auth_gssapi#207]
gssproxy credentials don't export their lifetimes.  Specifically, with the following C program:

```C
#include <assert.h>
#include <stdio.h>

#include <gssapi/gssapi.h>
#include <gssapi/gssapi_ext.h>

int main(int argc, char *argv[]) {
    OM_uint32 major, minor, lifetime = 7, inq_lifetime = 8;
    gss_key_value_set_desc store;
    gss_key_value_element_desc element;
    gss_cred_id_t cred;

    assert(argc == 2);

    element.key = "ccache";
    element.value = argv[1];
    store.count = 1;
    store.elements = &element;

    major = gss_acquire_cred_from(&minor, GSS_C_NO_NAME, 0, GSS_C_NO_OID_SET,
                                  GSS_C_BOTH, &store, &cred, NULL, &lifetime);
    assert(major == 0);

    major = gss_inquire_cred(&minor, cred, NULL, &inq_lifetime, NULL, NULL);
    assert(major == 0);

    printf("Lifetime: %d, %d\n", lifetime, inq_lifetime);
    
    return 0;
}
```

And this ccache:

```
klist t0_acquire.ccache 
Ticket cache: FILE:t0_acquire.ccache
Default principal: host/kdc.gssproxy.dev@GSSPROXY.DEV

Valid starting     Expires            Service principal
31/12/69 19:00:00  31/12/69 19:00:00  Encrypted/Credentials/v1@X-GSSPROXY:
```

we get "Lifetime: -1, -1".  (Which in turn means that `gssapi.Credentials(store={"ccache": "t0_acquire.ccache"}).lifetime` is None; i.e., not 0.)

Possibilities:
1. Leave it alone.  sweeper skips gssproxy credentials right now.  Tell admins not to use all three of sessions, unique ccache names, and gssproxy.
2. Attempt to init_sec_context with the credentials.  Results in a network request, which is annoying but workable, except that it's not clear what service to init against.
3. Something else?

**Comment by frozencemetery** [comment]
3. Set `GSS_USE_PROXY=yes` and `GPP_BEHAVIOR=REMOTE_FIRST` in sweeper.  This requires standard gssproxy configuration in order to work.
4. Provide handles for configuring the above env vars in the sweeper.
5. As 4 and 1, but tell admins to just set them appropriately before running sweeper.

**Comment by simo5** [comment]
I assume the configuration will be "right" already if gssproxy is working, however it may need the sweeper to run as a particular user.
So either 4 or 5 I would say.
The admin needs to tell the sweeper what user to use at the very least, so perhaps we could have an option to "--sweep-gssproxy-creds and one to --swith-to-user=<user>", of course the latter would require the sweeper to run as root, alternatively admins can add it in the proper user's crontab.

**Comment by frozencemetery** [comment]
It's more than user though.  It's also potentially socket or selinux context - or even program, which a python script can never match.

I think we're best off just documenting and explaining the situation (5).  Will submit a PR shortly.
