### ISSUE TITLE
Send final token (if any) in 200 OK response

### ISSUE THREAD

**Issue by frenche** [modauthgssapi/mod_auth_gssapi#21]
Hi Simo,

In some cases the client may want to inquire the context with 'gss_inquire_context' in order to get the 'src_name' of the initiator.
However, according to the spec (rfc2743) 'src_name' is valid only when 'open' (returned param) is true, meaning only when the context is fully established.

According to several tests I've made, in some flows the server still has a last token to send when 'gss_accept_sec_context' returns 'GSS_S_COMPLETE'.
Specifically it happens when SPNEGO mech is used or when raw KRB5 is used and 'mutual_auth' is requested.

With IIS, this last token is conveyed to the client via an "WWW-Authenticate: Negotiate" header sent in the 200 OK response.
This allows the client to fully establish the security context and initiator's 'src_name' can be inquired.

This one liner patch below fixes it for me:

diff --git a/src/mod_auth_gssapi.c b/src/mod_auth_gssapi.c
index e233110..ea989b1 100644
--- a/src/mod_auth_gssapi.c
+++ b/src/mod_auth_gssapi.c
@@ -561,7 +561,7 @@ static int mag_auth(request_rec *req)
     ret = OK;

 done:
-    if (ret == HTTP_UNAUTHORIZED) {
+    if (!is_basic) {
         if (output.length != 0) {
             replen = apr_base64_encode_len(output.length) + 1;
             reply = apr_pcalloc(req->pool, 10 + replen);

**Comment by frenche** [comment]
Which is wrong of course....
See below a second version (two liner this time), hopefully correct :)

```patch
diff --git a/src/mod_auth_gssapi.c b/src/mod_auth_gssapi.c
index e233110..aedc421 100644
--- a/src/mod_auth_gssapi.c
+++ b/src/mod_auth_gssapi.c
@@ -561,7 +561,7 @@ static int mag_auth(request_rec *req)
     ret = OK;

 done:
-    if (ret == HTTP_UNAUTHORIZED) {
+    if (ret == HTTP_UNAUTHORIZED || !is_basic) {
         if (output.length != 0) {
             replen = apr_base64_encode_len(output.length) + 1;
             reply = apr_pcalloc(req->pool, 10 + replen);
@@ -571,7 +571,7 @@ done:
                 apr_table_add(req->err_headers_out,
                               "WWW-Authenticate", reply);
             }
-        } else {
+        } else if (ret == HTTP_UNAUTHORIZED) {
             apr_table_add(req->err_headers_out,
                           "WWW-Authenticate", "Negotiate");
             if (cfg->use_basic_auth) {
```

**Comment by simo5** [comment]
I used a slightly different check, but the 2 are equivalent.
Thanks a lot for reporting this one.

**Comment by frenche** [comment]
Cool - much cleaner!

**Comment by frenche** [comment]
For future reference, it is also  documented in RFC 4559:
A status code 200 status response can also carry a "WWW-Authenticate" response header containing the final leg of an authentication.
