### ISSUE TITLE
Duplicate authentication for FallbackResource

### ISSUE THREAD

**Issue by alehaa** [modauthgssapi/mod_auth_gssapi#211]
If authentication is configured for a specific `<Location>` and `FallbackResource` is defined for a `<Directory>`, the authentication will be checked for the `<Location>` first, but after evaluating the "real" target, it will be checked for the `FallbackResource` a second time.

At the moment I can't tell if this is an issue of this or other modules. However, this leads to problems, e.g. in the following configuration, as the login form is not available due to an error 401:

```
DocumentRoot /var/www/sso/public

<Directory /var/www/sso/public>
    Require all granted
    FallbackResource /index.php
</Directory>

<Location "/">
    AuthType GSSAPI
    AuthName "Single Sign On"

    Require valid-user

    GssapiCredStore   keytab:/etc/apache2/http.keytab
    GssapiUseSessions On
    GssapiSessionKey  file:/var/run/apache2/krbSession.key
    GssapiLocalName   On

    Session           On
    SessionCookieName sso HttpOnly;Max-Age=37800

    # Show login form, if user is not logged in
    ErrorDocument 401 /login?%{QUERY_STRING}
</Location>

<Location ~ "/(login|assets)">
    Require all granted
    Session Off
</Location>
```

I would expect this configuration to require authentication for anything but the login form and assets. However, after granting access, it will be revoked because `/index.php` matches the first location:

```
[trace5] protocol.c(710): Request received from client: GET / HTTP/1.1
[debug]  mod_authz_core.c(820): AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[debug]  mod_authz_core.c(820): AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[debug]  mod_auth_gssapi.c(908): URI: /, no main, no prev
[info]   mod_auth_gssapi.c(105): NO AUTH DATA Client did not send any authentication headers
[trace3] request.c(119): auth phase 'check user' gave status 401: /
[trace4] util_expr_eval.c(845): Evaluation of string expression from /etc/apache2/sites-enabled/sso.conf:64 gave: /login?
[debug]  mod_authz_core.c(820): AH01626: authorization result of Require all granted: granted
[debug]  mod_authz_core.c(820): AH01626: authorization result of <RequireAny>: granted
[trace3] request.c(312): request authorized without authentication by access_checker_ex hook: /login
[debug]  mod_auth_gssapi.c(740): GSSapiImpersonate not On, skipping impersonation.
[debug]  mod_authz_core.c(820): AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[debug]  mod_authz_core.c(820): AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[debug]  mod_auth_gssapi.c(908): URI: /index.php, with main, no prev
[error]  mod_auth_gssapi.c(949): The main request is tasked to establish the security context, can't proceed!
[trace3] request.c(119): auth phase 'check user' gave status 401: /index.php
[trace3] request.c(368): fixups hook gave 401: /login
[trace4] util_expr_eval.c(845): Evaluation of string expression from /etc/apache2/sites-enabled/sso.conf:64 gave: /login?
[debug]  util_cookies.c(129): AH00009: ap_cookie: user '(null)' removed cookie: 'sso=;Max-Age=0;HttpOnly;Domain=fangmann-gmbh.de;Path=/;Max-Age=37800'
[trace3] http_filters.c(1128): Response sent with status 401, headers:
```

It seems, either this module is checking the internal request to `index.php`, even if it shouldn't, or there's some configuration missing to tell apache to not check authentication for subrequests - but I couldn't find any solution for this yet.

**Comment by alehaa** [comment]
I found a temporary fix. The problem was, that if `Satisfy Any` was set on `index.php`, all requests lost authentication, as anything resolved to this configuration via `FallbackResource`.

However, one can create a symlink to `index.php` and set the required configuration for this symlink. Thus, the login routes stay unauthenticated, while the rest gets authenticated. However, I think a more "permanent" solution would be good.

```
<Location ~ "/(login|assets)">
    Require all granted
    Session Off

    FallbackResource /login.php
</Location>

<Location "/login.php">
    Satisfy Any
    Session Off
</Location>
```

**Comment by simo5** [comment]
The correct and only way to deal with an authentication page is that the page itself is not authenticated, it should just set a session and redirect back to the authenticated area the original request came from after setting up the session cookie.

**Comment by alehaa** [comment]
That‘s what I tried to achieve, but it seems not to be possible if a front controller (e.g. for symfony) is involved.
