### ISSUE TITLE
Supporting Microsoft's Resource Based Constrained Delegation

### ISSUE THREAD

**Issue by adfel70** [modauthgssapi/mod_auth_gssapi#212]
Is there a plan to add support for resource based constrained delegation which was added in Windows Server 2012?

**Comment by simo5** [comment]
As far as I know there is nothing in mod_auth_gssapi that really need to be changed in order, for apache applications, to perform it. The plumbing needed will all be available in the GSSAPI library implementation and different actions should be taken in the application only.
+iboukris can you confirm ?

**Comment by iboukris** [comment]
Support for resource-based was added upstream MIT master, but it isn't in any release yet (you could build from source and test). Actually no different actions should be taken by the application, just use the delegated ccache to get a target resource, which now can also be in another realm.

**Comment by simo5** [comment]
Ok I take this as confirmation that n changes in mod_auth_gssapi are needed at this time.

**Comment by adfel70** [comment]
Thanks for the response. I am still having a problem, though, using this kind of delegation.

We tested 3 options:
1. **Unconstrained delegation:**
by selecting "Trust this user for delegation to any service (Kerberos only)" on the impersonator.
--> ```KRB5CCNAME``` variable was set with valid path to the ticket, and application works as expected.

2. **Kerberos Constrained Delegation (KCD):**
 - Selecting "Trust this user for delegation to specified services only" on the impersonator.
 - configuring relevant <directory> with Gssapi parameters (```GssapiUseS4U2Proxy On``` and so...)
--> Again, ```KRB5CCNAME``` variable was set with path to the ticket, and application works as expected.

3. **Resource Based Kerberos Constrained Delegation:**
 - On the impersonating service we turned off delegation by selecting "Do not trust this user for delegation".
 - Using powershell, configuring AllowedToActOnBehalfOfOtherIdentity on the backend service with impersonator service as attribute's value.
 - Relevant settings:
```
 Require valid-user
 AuthType GSSAPI
 GssapiCredStore keytab:/path/to/keytab/file
 GssapiDelegCcacheDir /var/run/httpd/krbcache
```

 --> ccachedir is empty and ```KRB5CCNAME``` was not set, so application cannot run.

 I guess the real problem here is that delegated ccache is empty, and if it was set, delegation was working transparently.
 I cant tell if ```Gssapi``` was configured incorrectly or problem is on ActiveDirectory side. Would be glad to receive your help :)
 Thanks.

**Comment by iboukris** [comment]
Looks like your MAG is not using an updated MIT lib.

**Comment by adfel70** [comment]
What is MAG?

**Comment by iboukris** [comment]
Short for mod_auth_gssapi module, you may need to use LD_LIBRARY_PATH or such.

**Comment by adfel70** [comment]
Oh I see. I forgot to mention that Apache and the resource service are both running on RHEL 7.4 machines. Do you suggest it may be an issue with```krb5-libs``` version? should it have support for RBKCD?

**Comment by iboukris** [comment]
See my initial comment, the krb5-libs should be v1.18 which is not released yet, I'd suggest to wait for the release and try.

**Comment by adfel70** [comment]
Ok. Finally got it :)
Thanks again, will wait for this release...
