### ISSUE TITLE
Chrome 42 on Windows 7 with Basic Auth: gss_accept_sec_context() failed: [No credentials were supplied, or the credentials were unavailable or inaccessible (Unknown error)]

### ISSUE THREAD

**Issue by devurandom** [modauthgssapi/mod_auth_gssapi#27]
When a Chrome 42.0.2311.135 browser on Windows 7 (Enterprise, 64-bit, build 7601) tries to use Basic Authentication against an Apache 2.4.10-10 (Debian 8 "Jessie") server with mod_auth_gssapi 1.2.0, authentication will fail and the server will log:
```
gss_accept_sec_context() failed: [No credentials were supplied, or the credentials were unavailable or inaccessible (Unknown error)]
```

I verified the issue on one of our user's computers, as well as in an own virtual machine.

The problem does not occur with Chrome 41 on Ubuntu 14.04, not with Firefox (any version) on Windows, Linux or Mac, and neither with Safari on iOS or MacOSX (after installing gss-ntlmssp 0.6.0).

**Comment by simo5** [comment]
What version of mod_auth_gssapi are you using ?
Can you pastge the configuration ?
Any chance you can grab the network traffic and see what's in the Authenticate headers and tell if there is any difference between 41 and 42 ? (I know how to do that in Firefox with the developers tools, but I don't use chrome)

**Comment by devurandom** [comment]
Version: 1.2.0

Config:
```
                <Location /auth/login/RemoteUser:self>
                        AuthName "…"

#                       AuthType Kerberos
#
#                       Krb5Keytab /etc/apache2/http.keytab

                        AuthType GSSAPI

                        GssapiCredStore keytab:/etc/apache2/http.keytab
                        GssapiCredStore ccache:MEMORY:user_ccache

                        GssapiBasicAuth On

                        GssapiConnectionBound On
                        Header set Persistent-Auth "true"

                        GssapiUseSessions On
                        Session On
                        SessionCookieName gssapi_session path=/;httponly;secure;

                        Require valid-user

                        ErrorDocument 401 /errordocuments/401.html
                </Location>
```

And regarding Chromium 41 vs. Chrome 42: As there is no login failure, I do not get a chance to have a look at the headers of the response to the original (unauthenticated) request.

In any case, my assumption is that it is somehow related to Windows, and not to the specific Chrome version. Maybe related to NTLM (i.e. gss-ntlmssp)?

**Comment by simo5** [comment]
We always offer Negotiate (we do not have any toggle to turn it off for now) so if your client prefers a Negotiate option and doesn't have credentials it may well fail.

I need a trace of the headers sent by the client to figure out if there is something we can do about it.

**Comment by simo5** [comment]
We changed quite a lot about negotiate including accepting raw ntlm when the Negotiate verb is used. I would guess this will fix these situations. Closing now, feel free to reopen if the latest code i master doesn't fix this.

**Comment by devurandom** [comment]
With v1.3.0 I now have the same problem also on Firefox 39.0. In addition, it seems to be stuck in some endless loop - I get a few hundred of these log lines per second:
```
[...] [auth_gssapi:error] [pid 12142] [client ...] gss_accept_sec_context() failed: [No credentials were supplied, or the credentials were unavailable or inaccessible (Unknown error)]
```

Windows 7 with Chrome still cannot login.

**Comment by devurandom** [comment]
With the following config, I get this error message instead:
```
gss_acquire_cred[_from]() failed to get server creds: [An unsupported mechanism was requested (Unknown error)]
```

```apache
                <Location /auth/login/RemoteUser:self>
                        AuthName "..."

#                       AuthType Kerberos
#
#                       Krb5Keytab /etc/apache2/http.keytab

                        AuthType GSSAPI

                        GssapiCredStore keytab:/etc/apache2/http.keytab
                        GssapiCredStore ccache:MEMORY:user_ccache

                        GssapiBasicAuth On

#                       GssapiConnectionBound On
#                       Header set Persistent-Auth "true"

#                       GssapiUseSessions On
#                       Session On
#                       SessionCookieName gssapi_session path=/;httponly;secure;

                        Require valid-user

                        ErrorDocument 401 /errordocuments/401.html
                </Location>
```

**Comment by simo5** [comment]
Add this:
GssapiAllowedMech krb5

Feel free to close the issue if it solves your problem.

**Comment by devurandom** [comment]
Indeed, that seems to fix it. So NTLMSSP is causing this? Do you have an explanation for this? Debugging this properly is important for me, since some of my users (namely iOS, iirc) required NTLMSSP, since their browsers did not authenticate over other mechanisms.

**Comment by devurandom** [comment]
More results from tests:
* Aborting the first authentication dialogue (the one without showing the `AuthName`) and then entering the password/username into the second dialogue (the one which shows the `AuthName`) allows me to login.
* Updating gss-ntlmssp from v0.6.0 to 6c1742fe5bad49d3ea176546fd6f929ae05f4e7d does not solve the issue.

**Comment by devurandom** [comment]
Updating mod_auth_gssapi to 4e7967e797e5c8912a67c0de8f172bb95b5172ff fixes the issue in Firefox for me.

**Comment by simo5** [comment]
It is not gss_ntlmssp fault. It is browsers fault. When they detect NTLM support they decide it is ok to ask users for passwords.

**Comment by simo5** [comment]
I guess it is time for 1.3.1
Does the last commit improve the situation with the other browsers ?

**Comment by devurandom** [comment]
So far this sounds exactly like what I want: Ask the user for a password. What goes wrong in the process?

> Does the last commit improve the situation with the other browsers ?

4e7967e797e5c8912a67c0de8f172bb95b5172ff does not fix the issue on Firefox 39.0 for me, sorry. My claim was wrong, probably caused by the removal of `/etc/gss/mech.d/ntlmssp.conf` not taking effect immediately, but only after a few restarts of the Apache HTTPd - or something similar.

Currently I have `/etc/gss/mech.d/ntlmssp.conf` enabled, `GssapiAllowedMech` unset, mod_auth_gssapi at https://github.com/modauthgssapi/mod_auth_gssapi/commit/4e7967e797e5c8912a67c0de8f172bb95b5172ff and gss-ntlmssp at 6c1742fe5bad49d3ea176546fd6f929ae05f4e7d and I experience the issue as described here:

> * Aborting the first authentication dialogue (the one without showing the `AuthName`) and then entering the password/username into the second dialogue (the one which shows the `AuthName`) allows me to login.

**Comment by devurandom** [comment]
More tests:
* Chromium 43.0.2357.130 presents me the auth dialogue without the `AuthName` and when I abort it, I see the 401 error page immediately. (Firefox 39.0 instead begins to ask me for my credentials - this time also showing me the `AuthName`.)

**Comment by simo5** [comment]
I guess I am not sure what kind of configuration you desire anymore.
If you enable NTLM auth then all browsers always try to ask you  for NTLM credentials and try NTLM auth, that is out of mod_auth_gssapi control. If you do not want browsers to try NTLM auth the only option is to not allow NTLM auth by setting "GssapiAllowedMech krb5" in the configuration.
What am I missing ?

**Comment by devurandom** [comment]
1. Authentication with NTLM does not work. Whatever I enter into the authentication dialogue I am being presented by Chrome or Firefox, the server will log abovementioned error message and authentication fails.
2. The dialogue displayed in this case does not show `AuthName`.
3. Safari on iOS and MacOSX did not support GSSAPI and/or Basic Auth, so I had to add NTLM to support those users (cf. https://github.com/modauthgssapi/mod_auth_gssapi/issues/13#issuecomment-84992704). That is the only reason I installed gss-ntlmssp.

**Comment by simo5** [comment]
NTLM works only if you have a local user file or Windbind is installed and joined to a domain.
Is this your case ?

**Comment by simo5** [comment]
It is unlikely that safari does not support basic auth but I do not have one and can't test.

**Comment by devurandom** [comment]
> NTLM works only if you have a local user file or Windbind is installed and joined to a domain.
> Is this your case ?

Yes, on my machine I run Winbind, have it joined into the Windows domain and I use it to authenticate against Active Directory.

The Windows machines, where Chrome had its problems on, are also joined into the same domain. I can confirm that Firefox on one of those machines was able to log into my webservice without asking for credentials (after downgrading mod_auth_gssapi to v1.2.0), which I assume means that GSSAPI authentication against the Active Directory server works.

The iOS / MacOSX devices are most probably not joined into the Windows domain.

**Comment by simo5** [comment]
So chrome fails ntlm auth with v1.3.0 and master, but works with 1.2.0 ?

**Comment by devurandom** [comment]
No. Firefox works with v1.2.0, but fails with v1.3.0. Chrome fails with both versions.

**Comment by simo5** [comment]
Ok I will need some time to get my hands on a Windows machine with Chrome and try that.
Firefox should be easier to deal with, hopefully I'll have som time next week.
