### ISSUE TITLE
Client GSSAPI mechanism for Basic auth

### ISSUE THREAD

**Issue by frenche** [modauthgssapi/mod_auth_gssapi#31]
Hello,

The following code section deals with Basic auth when 'init_sec_context()' returns 'GSS_S_CONTINUE_NEEDED':
https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/src/mod_auth_gssapi.c#L467

However, in practice I think it will probably never happen because we acquire client credentials and call 'init_sec_context()' with 'GSS_C_NO_OID' which usually defaults to KRB mech, and as we do not request 'mutual_req_flag' we should get 'GSS_S_COMPLETE' on the first call to 'init_sec_context()' (only SPNEGO and NTLM mechs would always return 'GSS_S_CONTINUE_NEEDED' on the first call although mutual auth was not requested).

That's the behavior I get in lab tests which matches RFC 2078, quote:

   The client calls GSS_Init_sec_context()  to establish a security
   context to the server identified by targ_name, and elects to set the
   mutual_req_flag so that mutual authentication is performed in the
   course of context establishment. GSS_Init_sec_context()  returns an
   output_token to be passed to the server, and indicates
   GSS_S_CONTINUE_NEEDED status pending completion of the mutual
   authentication sequence. Had mutual_req_flag not been set, the
   initial call to GSS_Init_sec_context()  would have returned
   GSS_S_COMPLETE status. The client sends the output_token to the
   server.

In my opinion - in order to give the client the best chances to succeed - we could specify SPNGO mech OID instead of 'GSS_C_NO_OID' when acquiring client credentials and when calling 'init_sec_context()'.

Thoughts?

Cheers,
Isaac B.

**Comment by frenche** [comment]
Little correction - we check for 'GSS_S_CONTINUE_NEEDED' after a first call to 'gss_accept_sec_context()' so even when mutual auth would have been requested or if SPNEGO was used with KRB inside we should get 'GSS_S_COMPLETE' on that first call in practice.

However, the idea is still the same that this code section will probably never be reached unless we use SPNEGO that could fail-over to NTLM - which in my opinion could be a good idea as it may give the client more chances to succeed.

Regards,
Isaac B.

**Comment by simo5** [comment]
Spnego is not necessary.
At acquire_cred[_with_password] time the mechglue knows which credentials are available and can select the appropriate mechanism. If only ntlmssp credentials are avasilable then it should try the NTLM mechanism automatically. In that case multiple roundtrips will occur.
I do not think we need to change anything here.

**Comment by frenche** [comment]
Hi,

On Mon, May 25, 2015 at 6:22 PM, simo5 <notifications@github.com> wrote:

> Spnego is not necessary.
> At acquire_cred[_with_password] time the mechglue knows which credentials
> are available and can select the appropriate mechanism. If only ntlmssp
> credentials are avasilable then it should try the NTLM mechanism
> automatically. In that case multiple roundtrips will occur.
> I do not think we need to change anything here.
>
AFAI recall, when I tested 'init_sec_context(GSS_C_NO_OID)' it never failed
over to NTLM (only if I chose SPNEGO).
I don't think it is that important but I'll test again and let you know.

Regards,
Isaac B.

**Comment by simo5** [comment]
On Mon, 2015-05-25 at 10:12 -0700, Isaac Boukris wrote:
> AFAI recall, when I tested 'init_sec_context(GSS_C_NO_OID)' it never failed
> over to NTLM (only if I chose SPNEGO).
> I don't think it is that important but I'll test again and let you know.

If you have krb5 creds it will not fail to NTLM, that is intentional, as
the kerberos credentials are clearly better and should always be used in
preference.
If you wan to force NTLM auth you just set only ntlmssp as
GssapiAllowMech, I do not see any scenario where falling back to NTLM
after krb failed would be desirable on the server side.

Simo.

-- 
Simo Sorce * Red Hat, Inc * New York

**Comment by frenche** [comment]
Hi again,

On Mon, May 25, 2015 at 8:26 PM, simo5 <notifications@github.com> wrote:

> On Mon, 2015-05-25 at 10:12 -0700, Isaac Boukris wrote:
> > AFAI recall, when I tested 'init_sec_context(GSS_C_NO_OID)' it never
> failed
> > over to NTLM (only if I chose SPNEGO).
> > I don't think it is that important but I'll test again and let you know.
>
> If you have krb5 creds it will not fail to NTLM, that is intentional, as
> the kerberos credentials are clearly better and should always be used in
> preference.
> If you wan to force NTLM auth you just set only ntlmssp as
> GssapiAllowMech, I do not see any scenario where falling back to NTLM
> after krb failed would be desirable on the server side.
>

I tried now with GssapiAllowMech only ntlmssp and basic-auth does not fail
over to ntlm, i get:

[Fri Jun 12 20:07:17.394324 2015] [auth_gssapi:error] [pid 5841]
[client 10.0.0.250:37037] gss_accept_sec_context() failed:
[No credentials were supplied, or the credentials were unavailable or
inaccessible (Unknown error)]

As far as I can tell from the tests, calling gss_init_sec_context with
GSS_C_NO_OID
on fedora is equivalent to calling it with gss_mech_krb5.
So frankly, it seem this loop section code over 'GSS_S_CONTINUE_NEEDED' in
the basic-auth context will never be reached

I tried to change the client calls to gss_init_sec_context to
gss_mech_spnego and I now get:

[Fri Jun 12 20:15:52.130698 2015] [auth_gssapi:error] [pid 6114]
[client 10.0.0.250:37040] gss_init_sec_context() failed:
[A supplied name was of an unsupported type (Invalid value in argument)]

I start to doubt if it is worth the effort, maybe we are better off by
calling explicitly gss_init_sec_context with gss_mech_krb5 and remove the
loop over ccontinue_needed as we expect it to complete right away.

Regards,
Isaac B.

**Comment by simo5** [comment]
We should use ntlmssp if that's the only allowed mechanism.
Also spnego would require continuation, and although the krb5 mechanism does not require looping today, it might in future (there are proposals in IETF). So I want to keep the code formally correct anyway.

**Comment by simo5** [comment]
Please open a new issue if basic auth does not work when ntlmssp is the only allowed mechanism

**Comment by frenche** [comment]
On Fri, Jun 12, 2015 at 9:42 PM, simo5 <notifications@github.com> wrote:

> We should use ntlmssp if that's the only allowed mechanism.
>
Note that we only specify the allowed_mechs when acquiring client creds,
not when calling init_sec_ctx.

> Also spnego would require continuation, and although the krb5 mechanism
> does not require looping today, it might in future (there are proposals in
> IETF). So I want to keep the code formally correct anyway.
>
Actually if krb5 is used inside spnego there will be no continuation since
we only loop on the response from server's accept_sec_ctx not on client's
response from init_sec_ctx, so in case of krb that will be complete right
away afair.

I'll open a new issue soon - thank you.
