### ISSUE TITLE
NTLM stopped working

### ISSUE THREAD

**Issue by frenche** [modauthgssapi/mod_auth_gssapi#42]
In the last changes we managed to break NTLM (both raw and negotiate).

When the client sends the second request with the challenge response we fail to accept the context with:

[Tue Jun 16 21:40:07.857590 2015] [auth_gssapi:error] [pid 8818] [client 10.0.0.250:37686] gss_accept_sec_context() failed: [Invalid credential was supplied (Not a user credential type)]

Maybe related to 'mc' cleanup or to changes related to credentials acquirement ( testing without cred_store).
Perhaps we should keep the acquired credentials with the context on 'mc' and release it along as well.

**Comment by simo5** [comment]
Can't reproduce here running with the commits in PR #44
Can you check if that makes it work for you ?

**Comment by frenche** [comment]
On Tue, Jun 16, 2015 at 10:36 PM, simo5 <notifications@github.com> wrote:

> Can't reproduce here running with the commits in PR #44
> <https://github.com/modauthgssapi/mod_auth_gssapi/pull/44>
> Can you check if that makes it work for you ?
>

Checking right now!

**Comment by simo5** [comment]
MAke sure you pull the latest code, I fixed a bug in the second patch that was causing a crash wioth raw NTLM

**Comment by frenche** [comment]
Ah, that was my bad.
Somehow my apache lost his settings where I exported NTLM_USER_FILE (no idea how).
Thanks and sorry for the noise.
