### ISSUE TITLE
Basic auth with NTLM backend

### ISSUE THREAD

**Issue by frenche** [modauthgssapi/mod_auth_gssapi#43]
Following the discussion at issue #31 it seem that when only ntlmssp mech is allowed then basic-auth fails although we have code to do gssapi dance if necessary.

I'll collect debugs as soon as master stabilizes as  currently NTLM does not work at all for me.

**Comment by simo5** [comment]
Testing with #44 on I find out that this is caused by SPNEGO being selected and used, and then failing when krb5 is attempted.
I think the best option here is to prevent basic_authfrom using spnego. I will attempt a patch shortly.
