### ISSUE TITLE
Option to Specify SPN to use (or 'Any')

### ISSUE THREAD

**Issue by chriswheeler** [modauthgssapi/mod_auth_gssapi#47]
I've moved from mod_auth_kerb to mod_auth_gssapi in a project I'm working on, and it works very well. Thank you.

However, it only works when the website is accessed via http://hostname/ or http://fqdn/. I assume the SPN is being picked up from the address used to access the site, and this isn't always the case, e.g. it could be accessed via http://www.alias.com/ - in which case currently authentication fails.

With mod_auth_kerb I could use the option KrbServiceName to specify which SPN to use, e.g.

KrbServiceName HTTP/hostname

Or even better was 

KrbServiceName Any

Is it possible to implement something similar in mod_auth_gssapi? 

Or... is it possible to tell Apache which SPN to use? I thought setting ServerName may work, but it appears not to.

**Comment by simo5** [comment]
mod_auth_gssapi picks whatever key in in your keytab, so an option to specify a SPN hould not be needed.
However if you are not using the fqdn on your client, then the *client* will not be able to acquire a ticket valid for the server. This is the same whether you use mod_auth_kerb or mod_auth_gssapi as the server has no way to influence how the client acquires a ticket. The only way a client know is to take the server name and go to the KDC to ask for a ticket in that name.

There is one case that may not be served well, and that is holding multiple keys for different hostnames in your keytab. Is this your situation ?
If so can you show me the apache log file with the error thrown by mod_auth_gssapi ?

**Comment by chriswheeler** [comment]
The keytab contains keys for the hostname, and the fqdn:

```
Keytab name: FILE:/etc/krb5.keytab
KVNO Timestamp         Principal
---- ----------------- --------------------------------------------------------
   2 01/07/15 15:51:12 HTTP/srv-server.company.local@COMPANY.LOCAL (des-cbc-crc)
   2 01/07/15 15:51:12 HTTP/srv-server.company.local@COMPANY.LOCAL (des-cbc-md5)
   2 01/07/15 15:51:12 HTTP/srv-server.company.local@COMPANY.LOCAL (aes128-cts-hmac-sha1-96)
   2 01/07/15 15:51:12 HTTP/srv-server.company.local@COMPANY.LOCAL (aes256-cts-hmac-sha1-96)
   2 01/07/15 15:51:12 HTTP/srv-server.company.local@COMPANY.LOCAL (arcfour-hmac)
   2 01/07/15 15:51:12 HTTP/srv-server@COMPANY.LOCAL (des-cbc-crc)
   2 01/07/15 15:51:12 HTTP/srv-server@COMPANY.LOCAL (des-cbc-md5)
   2 01/07/15 15:51:12 HTTP/srv-server@COMPANY.LOCAL (aes128-cts-hmac-sha1-96)
   2 01/07/15 15:51:12 HTTP/srv-server@COMPANY.LOCAL (aes256-cts-hmac-sha1-96)
   2 01/07/15 15:51:12 HTTP/srv-server@COMPANY.LOCAL (arcfour-hmac)
```

All users will be connected from machines logged onto the company.local DC, but will be using the url http://server.company.com/

server.company.com is added to IE's trusted sites, and windows integrated authentication enabled

http://srv-server/ authenticates correctly, as does http://srv-server.company.local/

http://server.company.com/ does not.

.htaccess looks like:

    AuthType GSSAPI
    GssapiCredStore keytab:/etc/krb5.keytab
    AuthName "Connect - Please enter your network username and password."
    Require valid-user

**Comment by chriswheeler** [comment]
I think I may have found a fix, or it may have been something else causing the issue, but it's now working.

I added the following in krb5.conf

    [libdefaults]
     ignore_acceptor_hostname = true

I also removed the Computer from AD, deleted the keytab and rejoined and recreated the keytab, so it could have been some other issue.

**Comment by chriswheeler** [comment]
Another thought - when you say it picks whichever key is in your keytab, does it just pick the first one, or does it try all of them until one works?

**Comment by simo5** [comment]
Yeah ignore_acceptor_name can be used when you have a key valid for multiple names, or the KDC handles aliases the server knows nothing about. It basically tells GSSAPI to try all keys in the keytab, and if one happens to be able to decrypt the incoming blobs just use that.
