### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Diak** [modauthgssapi/mod_auth_gssapi#58]
I have a CentOS 7 and i cannot install mod_auth_gssapi.

first, in the README you don't mention which packets we have to install to compile the module and  that we have to use autoconf before ./configure.

Then when I use autoconf command I have these errros : 
configure.ac:4: error: possibly undefined macro: AM_INIT_AUTOMAKE
  If this token and others are legitimate, please use m4_pattern_allow.
  See the Autoconf documentation.
configure.ac:12: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:16: error: possibly undefined macro: AM_CONDITIONAL

How can I fix it please ?

**Comment by simo5** [comment]
Can you grab the release tarball ?
It should have configure ready to be called.

**Comment by Diak** [comment]
To be honest i don't know what you mean by "grab the release tarball".
If you mean to "git clone" a tagged version like this link https://github.com/modauthgssapi/mod_auth_gssapi/tree/v1.3.1 i have the same problem.

**Comment by frenche** [comment]
Try here:
https://github.com/modauthgssapi/mod_auth_gssapi/releases

**Comment by Diak** [comment]
Ok thanks for the link. I'll try it tomorrow and i'll tell you how it works.
Thanks for the help.

PS : it's still missing the dependencies needed to be installed with yum (or apt-get) before installing mod_auth_gssapi to be sure the problem i may have tomorrow are not related to this but i will see ;)

**Comment by Diak** [comment]
The release tarball works well. Thanks a lot.
