### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Diak** [modauthgssapi/mod_auth_gssapi#59]
Is it planned to release an Apache for Windows compilable or binary version of mod_auth_gssapi ?

**Comment by simo5** [comment]
I do not have any experience with it, but if someone were to propose patches to make it compile in Windows I'd have no problems integrating them.

**Comment by Diak** [comment]
I do not have it anymore unfortunately... 
Thanks anyway

**Comment by simo5** [comment]
Closing this one, if someone has patches they'll open a PR in future.
