### ISSUE TITLE
Module does not support multi-trip GSS authentication?

### ISSUE THREAD

**Issue by spaetow** [modauthgssapi/mod_auth_gssapi#61]
We've just tried to use this module with a GSSAPI mechanism that uses multiple roundtrips for authentication. This apparently segfaults. Can you confirm whether the module supports multiple roundtrips for GSSAPI authentication (as opposed to Kerberos, which requires only one round trip)?

**Comment by simo5** [comment]
Read this please:
https://github.com/modauthgssapi/mod_auth_gssapi#gssapiconnectionbound

What version did you try ?
If you had a segfault on the latest version can you please share the backtrace, I'd like to fix any potential segfault.

**Comment by alejandro-perez** [comment]
I tested it, and it works :)

**Comment by spaetow** [comment]
Alex, so it was that GssapiConnectionBound setting? Excellent, good to know that! :+1: :-)

Simo, I'll close this then. :-)

**Comment by alejandro-perez** [comment]
Yes, indeed it was. And not using the GssapiCredStore, otherwise it stucks to kerberos and not use any other gss mechanism.

**Comment by spaetow** [comment]
I'll document this for the Moonshot wiki! :-)

**Comment by frenche** [comment]
Hi, 

Still would be nice if you could share the configuration that caused the segfault and the backtrace so we could try to address it as suggested.

Thanks!

**Comment by spaetow** [comment]
I'll try to reproduce for you... installing an Ubuntu 14 image at the moment.
