### ISSUE TITLE
Can't install on Red Hat 6.7 (Santiago)

### ISSUE THREAD

**Issue by liepa** [modauthgssapi/mod_auth_gssapi#66]
I have Redhat 6.7 (Santiago) and I tried to install this module by:
1) installing autoconf (2.69)
2) autoconf
3) ./configure - and on this I get error:

./configure: line 2220: syntax error near unexpected token `-Wall'
./configure: line 2220: `AM_INIT_AUTOMAKE(-Wall foreign subdir-objects tar-pax)'

**Comment by liepa** [comment]
Was able to ./configure using "autoreconf -fi" instead of "autoconf", but now when calling make I get error. Steps: 
1) autoreconf -fiv
   had to make m4 folder for autoceconf to work
2) ./configure
3) make - get this error:

        mod_auth_gssapi.c: In function ‘use_s4u2proxy’:
        mod_auth_gssapi.c:634: error: ‘struct mag_config’ has no member named ‘use_s4u2proxy’
        mod_auth_gssapi.c:635: error: ‘struct mag_config’ has no member named ‘deleg_ccache_dir’
        make[2]: *** [mod_auth_gssapi_la-mod_auth_gssapi.lo] Error 1

**Comment by simo5** [comment]
sorry @liepa but i do not think mod_auth_gssapi builds on EL6. We require a newer version of MIT kerberos than available there.
I think I tried to stay compatible, and the errors you see are a failure to stay compatible.
I will see if I can get a patch to make it build, but several features will be missing then.

**Comment by simo5** [comment]
I just pushed a commit in master that should fix this buid issue.
LLet me know how it goes.

**Comment by liepa** [comment]
It worked, thanks!

**Comment by liepa** [comment]
Hi,
what is alternative way of using GssapiCredStore to specify keytab file?

As I see in code it is skipped for rhel 6:
#ifdef HAVE_CRED_STORE
    AP_INIT_FLAG("GssapiUseS4U2Proxy", mag_use_s4u2p, NULL, OR_AUTHCFG,
                  "Initializes credentials for s4u2proxy usage"),
    AP_INIT_ITERATE("GssapiCredStore", mag_cred_store, NULL, OR_AUTHCFG,
                    "Credential Store"),
    AP_INIT_RAW_ARGS("GssapiDelegCcacheDir", mag_deleg_ccache_dir, NULL,
                     OR_AUTHCFG, "Directory to store delegated credentials"),
#endif

Thanks!

**Comment by simo5** [comment]
On Tue, 2016-01-26 at 06:52 -0800, Jānis Liepa wrote:
> Hi,
> what is alternative way of using GssapiCredStore to specify keytab file?
> 
> As I see in code it is skipped for rhel 6:
> #ifdef HAVE_CRED_STORE
>     AP_INIT_FLAG("GssapiUseS4U2Proxy", mag_use_s4u2p, NULL, OR_AUTHCFG,
>                   "Initializes credentials for s4u2proxy usage"),
>     AP_INIT_ITERATE("GssapiCredStore", mag_cred_store, NULL, OR_AUTHCFG,
>                     "Credential Store"),
>     AP_INIT_RAW_ARGS("GssapiDelegCcacheDir", mag_deleg_ccache_dir, NULL,
>                      OR_AUTHCFG, "Directory to store delegated credentials"),
> #endif


Set KRB5_KTNAME in the encironment before running apache.
(OR KRB5_CLIENT_KTNAME if you need it for initiation)

Simo.


-- 
Simo Sorce * Red Hat, Inc * New York
