### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bakerkj** [modauthgssapi/mod_auth_gssapi#68]
Hi,

Without change 855341bf3b39fe5e5b9abf299563e0d09c4861a3 expired sessions do not appear to reauthenticate in 1.3.1.  Is there a chance of another release?

Thanks!

-- ken

**Comment by simo5** [comment]
@bakerkj as soon as I land #65 I will make a release.

**Comment by bakerkj** [comment]
I'm looking forward to it.  Thanks!

**Comment by simo5** [comment]
v1.3.2 has been released.
