### ISSUE TITLE
Saving of Credentials and Basic Authentication

### ISSUE THREAD

**Issue by amessina** [modauthgssapi/mod_auth_gssapi#70]
As suggested by @frenche in #69, the discussion is moved here:
> I think the discussion of which kind of credentials we want to save in basic-auth should be moved to another issue.
> In general, in basic-auth we have the following options:

> * Store user's TGT acquired with password as mod_auth_kerb does.
> * Store user's TGT delegated via regular delegation as mod_auth_gssapi does today.
> * Store constrained delegated credentials only when S4U2Proxy is available.
>
> Note that the two first should be equivalent, that is why PHP's PDO failure is strange.
> We know the ccache is good before calling PHP's PDO and we know it is good after the script runs (as you can run 'klist' on it or run the ldapsearch command from CLI after the script has run).

> Maybe for some reason, PHP's PDO tries to read another ccache file although KRB5CCNAME points to the correct one (maybe strace could help, but it isn't easy).

For my situation described in #69, I'm looking for the end-user functionality that mod_auth_kerb provides: the ability to fallback to Basic auth *and* save the credentials in a way that they can be used for further access to downstream systems (PostgreSQL, LDAP, etc.).  This is something like the first option above.

**Comment by frenche** [comment]
Thanks @amessina 

To clarify, I think issue #69 is not likely to be related to this one.
Let's hope the krb debugs will help to get a better understanding.

**Comment by frenche** [comment]
Hi @simo5, following out discussion over #69 please see the cleanup I meant, at:
https://github.com/frenche/mod_auth_gssapi/commit/6753fe12609ee6d0a75048e7973bcb31c89abdaa

**Comment by simo5** [comment]
Please open a PR with that code.

**Comment by frenche** [comment]
Done!
