### ISSUE TITLE
Add a tunable to allow session cookie expiration to be shorter (admin defined)

### ISSUE THREAD

**Issue by simo5** [modauthgssapi/mod_auth_gssapi#73]
In some web apps you want to expire the credentials much sooner than the ticket expiration is set to.
A tunable will allow to set a maximum validity time, and cap the session cookie expiration date.

**Comment by amessina** [comment]
I'm not sure if it's possible or the right thing to do, but I'm thinking that it would be good to enable setting the kerberos ticket lifetime to something shorter and having the session cookie expiration to the same thing.  Maybe that's what you were thinking.

**Comment by simo5** [comment]
Yes, that's the idea.
It will cause the browser to do a full reauth more often, OTOH if the user deleted the credentials locally the brower will fail as expected in a reasonable timeframe.

**Comment by frenche** [comment]
Perhaps we could enforce mod_session's expiry which the admin can limit via SessionMaxAge directive.
Something like (not really tested):
```diff
diff --git a/src/sessions.c b/src/sessions.c
index c31a51a..eedee16 100644
--- a/src/sessions.c
+++ b/src/sessions.c
@@ -215,7 +215,11 @@ void mag_attempt_session(struct mag_req_cfg *cfg, struct mag_conn *mc)

     gsessdata.established = mc->established?1:0;
     gsessdata.delegated = mc->delegated?1:0;
-    gsessdata.expiration = mc->expiration;
+    if (sess->expiry != 0)
+        gsessdata.expiration = mc->expiration < apr_time_sec(sess->expiry) ?
+                               mc->expiration : apr_time_sec(sess->expiry);
+    else
+        gsessdata.expiration = mc->expiration;
     if (OCTET_STRING_fromString(&gsessdata.username, mc->user_name) != 0)
         goto done;
     if (OCTET_STRING_fromString(&gsessdata.gssname, mc->gss_name) != 0)

**Comment by mrogers950** [comment]
I tested the above patch, and it works for influencing the cookie's expiry from SessionMaxAge. However it does not adjust GSS_SESSION_EXPIRATION. Should it?

**Comment by simo5** [comment]
I guess what we should do is change the value of mc->expiration if sess->expiry is set and is greater than mc->expiration, so that following authentications will use that value and it will be set in the session cookie and all will be consistent.

**Comment by frenche** [comment]
Yea, this looks good.
