### ISSUE TITLE
GssapiNegotiateOnce

### ISSUE THREAD

**Issue by xdaxdb** [modauthgssapi/mod_auth_gssapi#74]
I've been trying different settings and I am not able to use GssapiNegotiateOnce:

"Invalid command 'GssapiNegotiateOnce', perhaps misspelled or defined by a module not included in the server configuration."

CentOS 7.2

Name        : mod_auth_gssapi
Version     : 1.3.1
Release     : 1.el7
Architecture: x86_64

**Comment by frenche** [comment]
I think GssapiNegotiateOnce was only introduced in 1.3.2 version, see:
https://github.com/modauthgssapi/mod_auth_gssapi/releases

**Comment by xdaxdb** [comment]
Well, that would explain it. Thanks.
