### ISSUE TITLE
Fall-back to LDAP

### ISSUE THREAD

**Issue by xdaxdb** [modauthgssapi/mod_auth_gssapi#75]
I see a few references to falling back to basic, but if I understand correctly that just means to prompt for user/password but it still uses gssapi.

How could I fall-back to an authentication type other than gssapi (LDAP) for some clients who are coming from workstations in a heavily restricted external AD domain that can't do kerberos with me for reasons.

**Comment by simo5** [comment]
Set mod auth gssapi's basic auth to no, and configure another module to perform it.

**Comment by simo5** [comment]
Actually re-reading about the AuthType directive, I think there is no fallback/stacking support in Apache, so you have to configure different directories if you want to have multiple authentication choices.
This is more a q. for Apache then mod_auth_gssapi, so I'll close this issue.
