### ISSUE TITLE
Fallback to AuthBasicProviders

### ISSUE THREAD

**Issue by devurandom** [modauthgssapi/mod_auth_gssapi#8]
I am searching for a way to fallback to `AuthBasicProvider`s if the user is unknown to mod_auth_gssapi. In particular I want to use [the Redmine PerlAuthenHandler][1], which is somehow hooked into the `AuthBasicProvider` list by mod_perl2.

It seems that currently both mod_auth_basic as well as mod_auth_gssapi prohibit this by declining authentication if the configured `AuthType` does not match. From a naive point of view implementing fallback from `GSSAPI` to `Basic` appears to be easy, though: If there is no Kerberos ticket, mod_auth_gssapi has to fallback to `WWW-Authenticate: Basic` anyway, so if the user it gets is unknown, it could just pass on the user/password to mod_auth_basic and its registered  `AuthBasicProvider`s.

To give you a better idea of my situation, here is (part of) my config:
```apache
PerlLoadModule Apache::Authn::RedmineAuthOnly

<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin ???
                ServerName ???
                DocumentRoot /usr/share/redmine/public

                ErrorLog ${APACHE_LOG_DIR}/error.???.log
                CustomLog ${APACHE_LOG_DIR}/access.???.log combined

                <Location />
                        AuthName "???"

                        AuthType GSSAPI

                        GssapiCredStore keytab:/etc/apache2/http.keytab

                        GssapiConnectionBound On
                        Header set Persistent-Auth "true"

                        GssapiUseSessions On
                        Session On
                        SessionCookieName gssapi_session path=/;httponly;secure;

#                       AuthType Basic
#                       AuthUserFile /dev/null
#                       PerlAccessHandler Apache::Authn::RedmineAuthOnly::access_handler
#                       PerlAuthenHandler Apache::Authn::RedmineAuthOnly::authen_handler

                        RedmineDSN "DBI:mysql:database=???;host=localhost"
                        RedmineDbUser "???"
                        RedmineDbPass "???"

                        Require valid-user
                </Location>
```

[1]: https://github.com/redmine/redmine/blob/master/extra/svn/Redmine.pm

**Comment by devurandom** [comment]
I tried the following setup (excerpt):
```
               Redirect temp /login /login-gssapi

               RewriteEngine On
               RewriteRule /login-gssapi /login [L,QSA]
               RewriteRule /login-basic /login [L,QSA]

                <Location /login-gssapi>
                        AuthType GSSAPI
                        ErrorDocument 401 /login-basic
                </Location>

                <Location /login-basic>
                        AuthType Basic
                </Location>
```

The intention was that requests to `/login` are redirected to `/login-gssapi`, if authentication fails there, the server forwards it internally to `/login-basic` and on success for both locations it will internally treat it as a request to `/login`, so the app keeps working as before.

This does not work. The primary issue is that `ErrorDocument` apparently already kicks in on the first `GET`, before mod_auth_gssapi can request any credentials from the browser. Commenting out that part for testing purposes, the `RewriteRule` was executed (as was logged in the error log with trace enabled), but then somehow ignored anyway, resulting in a 404.

**Comment by simo5** [comment]
I am pushing a patch that should address your issue.
Let me know if it is sufficient to you.

**Comment by devurandom** [comment]
I am currently unable to configure this properly (authentication against AD and fallback to Redmine Perl module). I get some weird error when trying to login with my AD credentials:
```text
[authn_core:error] … AH01796: AuthType GSSAPI configured without corresponding module
```

The config is now:
```apache
                <Location /login>
                        AuthName "???"

                        AuthType GSSAPI
                        AuthUserFile /dev/null

                        GssapiBasicAuth Forward
                        GssapiCredStore keytab:/etc/apache2/http.keytab

                        GssapiConnectionBound On
                        Header set Persistent-Auth "true"

                        GssapiUseSessions On
                        Session On
                        SessionCookieName gssapi_session path=/;httponly;secure;

                        PerlAccessHandler Apache::Authn::RedmineAuthOnly::access_handler
                        PerlAuthenHandler Apache::Authn::RedmineAuthOnly::authen_handler

                        RedmineDSN "DBI:mysql:database=???;host=localhost"
                        RedmineDbUser "???"
                        RedmineDbUser "???"
                        RedmineDbPass "???"

                        Require valid-user
                </Location>
```

I also tried replacing `AuthType GSSAPI` with `AuthType Basic`, but that seems to skip mod_auth_gssapi entirely.

As we decided to switch from Redmine to [Phabricator](http://phabricator.org/), which supports different authentication methods, each with a custom route / URI, we do not need the fallback option anymore. The AD route is secured with `AuthType GSSAPI` and `GssapiBasicAuth On`, and everyone else logs in via the regular webform. However, if you want me to test this further, I would be willing to do so. Please instruct me how this is intended to be setup.

On a sidenote: Could you please document `GssapiBasicAuth On`? The example currently only mentions `GssapiBasicAuth Forward` and I only found out how to enable "normal" mode by looking at the code.

**Comment by simo5** [comment]
Thanks for testing, I think it may be due to the fact I require the AuthType to be the string GSSAPI, basic auth may require the same. Let me check the code, I'll see if I can come up with a patch to properly handle that.

**Comment by simo5** [comment]
After some more testing and fiddling I decided to remove the Forward option entirely.
Apache modeules are simply not really made for stacking and although I succeeded in getting both mod_auth_basic and mod_auth_gssapi to act, they didn't really work together.

**Comment by devurandom** [comment]
Thanks!
