### ISSUE TITLE
GssapiUseSessions feature does not populate response cookie.

### ISSUE THREAD

**Issue by dasbh** [modauthgssapi/mod_auth_gssapi#98]
I have following http config

```
<Location /private>
    AuthType GSSAPI
    AuthName "GSSAPI Single Sign On Login"
    GssapiSSLonly Off
    GssapiUseSessions On
    Session On
    SessionCookieName gssapi_session path=/;httponly;
    GssapiCredStore ccache:/apps/httpd2/logs/httpd_krb5_ccache
    GssapiCredStore client_keytab:/home/user/keytab
    GssapiCredStore keytab:/home/user/keytab
    GssapiBasicAuth Off
    GssapiAllowedMech krb5
    Require valid-user
</Location>
```

After the successful negotiate authentication cookie does not get sent in response as expected rather  the server sends clear cookie command.

Expected response

```
Set-Cookie:"gssapi_session=MagBearerToken=QaBD.....;path=/;httponly;"
```

Actual response:

```
Set-Cookie:"gssapi_session=;path=/;httponly; gssapi_session=;path=/;httponly;"
```

Note that the **MagBearerToken=token** is missing and also note that the **gssapi_session** clear cookie command is sent twice in the response.

From debugging it appears that adding the guard **mc->ccname &&** in the code below resolved the issue however I do not have a pull request as I am uncertain of the intended usage, the intended valid configuration and the correct logic.

sessions.c:239
```
    if (mc->ccname && OCTET_STRING_fromString(&gsessdata.ccname, mc->ccname) != 0)
        goto done;
```

Additionally I note that there is no automated test for this feature.

With the additional guard I found that the cookie gets set correctly however the cookie is set twice in the response header.

ie I see something like this ... 

```
Set-Cookie:"gssapi_session=MagBearerToken=QaBD.....;path=/;httponly;gssapi_session=MagBearerToken=QaBD.....;path=/;httponly;"
```

However as mentioned I am not confident about this as a solution.

**Comment by simo5** [comment]
@frozencemetery this looks like it was introduced by your patch, can you take a look ?

**Comment by frozencemetery** [comment]
The double Set-Cookie is present in 258ac54878fc98cfd0e7c04216189561172b55bd, so that's not introduced by the unique ccaches, and doesn't break anything (though we should probably still fix it).

However, not setting MagBearerToken is new and breaking with my changes.  I will investigate further.

**Comment by simo5** [comment]
Yeah I didn't mean you should fix the double set, but if you do kudos! :-)
For the MagBerareToken I think you just need to set an empty value if no ccname is generated (it happens when no delegation is requested/configured), and if you find the empty string on retrieval you just set ccname to NULL as well.

**Comment by frozencemetery** [comment]
(I did look into the double-set, but couldn't find anything obvious since we only have the one callsite.)
